// AUTO-GENERATED from PDF — DO NOT EDIT MANUALLY
// Source: 10.02.26_crudo_psicologo.pdf

export type EjeType = 'D' | 'I' | 'S' | 'C';
export type MotorType = 'Rápido' | 'Medio' | 'Lento';

export interface GuiaRow {
  situacion: string;
  activador: string;
  desmotivacion: string;
}

export interface Checklist {
  antes: string;
  durante: string;
  despues: string;
}

export interface ArchetypeData {
  id: string;
  eje: string;
  motor: string;
  label: string;
  perfil: string;
  bienvenida: string;
  wow: string;
  motorDesc: string;
  combustible: string;
  grupoEspacio: string;
  corazon: string;
  palabrasPuente: string[];
  palabrasRuido: string[];
  guia: GuiaRow[];
  reseteo: string;
  ecos: string;
  checklist: Checklist;
}

export const ARCHETYPE_DATA: Record<string, ArchetypeData> = {
  impulsor_dinamico: {
    id: `impulsor_dinamico`,
    eje: `D`,
    motor: `Rápido`,
    label: `Impulsor Dinámico`,
    perfil: `Acción Directa y Resolución Inmediata`,
    bienvenida: `Este mapa nos permite asomarnos a la manera en que {nombre} tiende a vivir y sentir el deporte hoy. Al igual que un mapa de navegación no dice si un terreno es "bueno" o "malo", sino qué equipo necesitamos para recorrerlo mejor, este informe brinda herramientas para que el deporte sea un espacio de disfrute y no de presión. Nota fundamental: Este informe no evalúa el talento ni predice el éxito deportivo. Sus hallazgos son probabilísticos y dinámicos: describen tendencias actuales que evolucionarán junto con la maduración natural de {nombre}. No son rasgos inamovibles, sino una fotografía de su sintonía presente.`,
    wow: `En el mito de la nave Argo, cada tripulante tenía una naturaleza única. {nombre} ocupa naturalmente el lugar de quien activa el movimiento. No es alguien que espere a que las cosas sucedan; su sistema está diseñado para ser la chispa que inicia la acción. Es probable que notes que {nombre} es ese tripulante que, en los momentos de mayor duda o cuando el juego se detiene, toma la iniciativa para reiniciar el avance. Su contribución no es solo física, es una energía de resolución que empuja a toda la tripulación hacia adelante. No busca mandar por el simple hecho de mandar, sino porque su naturaleza siente que el movimiento es el estado más seguro para el equipo. Su "superpoder" es la valentía de decidir en el instante.`,
    motorDesc: `Técnicamente, el perfil de {nombre} se asocia a un Motor Rápido. En la vida cotidiana, esto significa que la distancia entre su percepción y su acción es casi inexistente. Para él, aprender es experimentar. No necesita que le expliquen la teoría del pase en una pizarra durante diez minutos; su cerebro procesa la información mucho mejor mientras se está moviendo. Si lo ves inquieto durante las charlas técnicas, no es falta de interés o de respeto, es su motor interno diciendo: "Ya entendí el qué, ahora déjame probar el cómo". Acción de Sintonía: Cuando necesites darle una indicación, hazlo mientras él tiene el balón o está en movimiento. La información "viaja" mejor en su sistema cuando su cuerpo está activo.`,
    combustible: `¿Qué hace que {nombre} quiera volver el próximo domingo? Su combustible principal es el sentido de progreso y el impacto. Él necesita sentir que sus acciones producen un cambio visible en el juego. Se siente vibrante cuando puede decir: "Yo logré que esto pasara". Feedback de Sintonía: Él es muy sensible al reconocimiento de su iniciativa. Valora más que le digas "Me encantó cómo te animaste a intentar ese pase" que un simple "Muy bien jugado". El elogio debe validar su valentía, no solo el resultado.`,
    grupoEspacio: `En el equipo: {nombre} se vincula a través de la acción compartida. Su forma de ser "amigo" de sus compañeros es pasándoles el balón o defendiendo una posición difícil. Su lealtad se demuestra en el esfuerzo físico conjunto más que en las palabras. En el espacio: Tiende a preferir los escenarios de alta intensidad y espacios dinámicos. Le gusta el "ida y vuelta". Los ejercicios estáticos o las filas largas para esperar un turno son su mayor fuente de fricción emocional; es ahí donde su sintonía suele decaer y puede aparecer la distracción.`,
    corazon: `Para sintonizar con él, el adulto debe aprender a traducir lo que ve: Lo que parece: Impaciencia o ganas de "querer hacer todo solo". Lo que realmente es (La Intención): Un deseo profundo de eliminar la incertidumbre. Cuando el juego se vuelve caótico, {nombre} siente que debe actuar rápido para que el equipo no pierda el rumbo. Su impulso es un acto de cuidado hacia la misión del equipo. El Termómetro de la Frustración: Su frustración es "hacia afuera". Si lo ves con gestos bruscos o aumentando su velocidad de forma errática, es una señal de que su sistema se ha sobrecalentado. No es "mal carácter", es saturación de intensidad.`,
    palabrasPuente: ["Impacto", "Iniciativa", "Tú decides", "Adelante", "Resolución"],
    palabrasRuido: ["Cuidado", "Espera", "Cálmate", "Pórtate bien", "No te \narriesgues"],
    guia: [
      { situacion: "Mantenga su conexión Proponerle", activador: "una responsabilidad clara y con impacto (ej: \"Tu rol es presionar la salida\").", desmotivacion: "Consignas ambiguas o pasivas como \"pórtate bien\" o \"juega con calma\".." },
      { situacion: "Recupere su seguridad Validar", activador: "una decisión específica que haya tomado, aunque no haya salido perfecta.", desmotivacion: "Críticas basadas en la emoción o comparaciones con otros niños.." },
      { situacion: "Transite un cambio de", activador: "rol Explicar el sentido estratégico del cambio (ej: \"Te necesito aquí para cubrir este hueco\").", desmotivacion: "Realizar cambios sin una breve explicación que le dé sentido a su nueva posición.." }
    ],
    reseteo: `Cuando {nombre} comete un error, su tendencia es rumiar la frustración a través de la intensidad física. Estrategia de Reseteo: No detengas el flujo para explicarle el error técnico en ese momento. Su motor rápido necesita "limpiar" la sensación de fallo con una nueva acción exitosa. Dale un objetivo pequeño y alcanzable de inmediato (ej: "¡Bien intentado! Ahora, busca este pase"). Esto le permite volver emocionalmente al juego sin quedar anclado en la culpa.`,
    ecos: `Aunque este informe nace del deporte, estas tendencias de ritmo son parte de su forma de procesar el mundo: En casa: Es probable que prefiera instrucciones segmentadas de una en una. Si le das tres órdenes juntas, su motor rápido se activará con la primera y olvidará las otras dos. En la escuela: Su estilo de aprendizaje es el "hacer". Los proyectos prácticos o los experimentos donde pueda ver resultados inmediatos son su zona de mayor éxito y disfrute.`,
    checklist: {
      antes: `Acordad un único objetivo basado en su intención (ej: "Hoy el objetivo es que disfrutes buscando espacios"). `,
      durante: `Practica el Silencio Aliado. Confía en su capacidad para resolver. Tu presencia tranquila es su mejor apoyo. `,
      despues: `Respeta los 20 minutos de enfriamiento. Deja que su motor baje de revoluciones antes de hablar del juego. Comienza siempre preguntando: "¿Qué fue lo que más te divirtió hoy?".`,
    },
  },
  impulsor_decidido: {
    id: `impulsor_decidido`,
    eje: `D`,
    motor: `Medio`,
    label: `Impulsor Decidido`,
    perfil: `Iniciativa Estratégica y Ejecución con Propósito`,
    bienvenida: `Este mapa es una herramienta para entender cómo {nombre} se conecta con el deporte en esta etapa de su vida. No es una definición de su personalidad para siempre, sino una "fotografía del presente" que nos ayuda a ajustar nuestra comunicación con él. Nota de Seguridad: Este informe no evalúa el talento. Su único fin es que {nombre} se sienta más comprendido y disfrute más de cada partido, reduciendo la fricción emocional entre sus necesidades y nuestras expectativas.`,
    wow: `En la tripulación de la Nave Argo, {nombre} es quien asegura que el avance sea firme y con dirección. No es el tripulante que salta al agua sin mirar, sino aquel que, una vez que entiende hacia dónde vamos, pone toda su determinación para que la nave llegue a destino. Es probable que notes que {nombre} muestra una confianza muy alta cuando el plan está claro. Su valor para el grupo reside en su consistencia: una vez que decide que es el momento de actuar, lo hace con una fuerza y un enfoque admirables. No busca la acción por el ruido, sino por el logro. Su presencia en el equipo aporta seguridad en la ejecución; es quien transforma la intención en resultados tangibles.`,
    motorDesc: `Técnicamente, el perfil de {nombre} se asocia a un Motor Medio. Esto significa que su sistema prefiere un ritmo de "procesar para ejecutar". A diferencia de los perfiles que actúan por puro instinto, {nombre} tiene un breve tiempo de análisis interno. Él observa la jugada, evalúa sus opciones y luego actúa con decisión. Bajada humana: Si a veces parece que tarda un segundo más en arrancar, no es falta de ganas, es su cerebro asegurándose de que la acción sea la correcta. Acción de Sintonía: Evita pedirle que "sea más rápido" de forma genérica. Dale claridad sobre el objetivo y verás cómo su velocidad natural aumenta al sentirse seguro.`,
    combustible: `¿Qué motiva a {nombre}? Su combustible es la eficacia. Le gusta sentir que es competente y que sus acciones tienen sentido dentro del juego. Feedback de Sintonía: Valora mucho que reconozcas la calidad de su decisión. En lugar de decirle "¡Qué golazo!", prueba con: "Me gustó mucho cómo esperaste el momento justo para patear". Esto valida su proceso mental y refuerza su confianza.`,
    grupoEspacio: `En el equipo: {nombre} tiende a vincularse a través de la colaboración orientada a tareas. Se siente cómodo con compañeros que respetan su espacio y que cumplen con su parte del plan. No es necesariamente el que más habla en el vestuario, pero es quien lidera con el ejemplo cuando el balón empieza a rodar. En el espacio: Prefiere los contextos donde hay cierto orden táctico. Se siente cómodo en su zona asignada y fluye mejor cuando el campo no es un caos total. El desorden excesivo o la falta de reglas claras en un ejercicio pueden frustrarlo y apagar su iniciativa.`,
    corazon: `Para sintonizar con él, debemos mirar más allá de la conducta: Lo que parece: A veces puede parecer testarudo o demasiado serio. Lo que realmente es (La Intención): Un deseo de hacerlo bien. {nombre} tiene un alto nivel de auto-exigencia. Si se muestra rígido, es porque está intentando mantener el control de la situación para asegurar el resultado para su equipo. El Termómetro de la Frustración: Su frustración suele ser silenciosa al principio, pero se nota en una "tensión física" aumentada. Si empieza a jugar con demasiada fuerza, es señal de que necesita que le devuelvas la calma con una instrucción lógica.`,
    palabrasPuente: ["Estrategia", "Objetivo", "Tú sabes cómo", "Paso a \n\npaso", "Efectivo"],
    palabrasRuido: ["Como sea", "Improvisa", "Apúrate", "No pienses", "Suéltate"],
    guia: [
      { situacion: "Mantenga su conexión Darle", activador: "un objetivo técnico que requiera su potencia y decisión.", desmotivacion: "Cambiar las reglas del juego a mitad del entrenamiento sin aviso.." },
      { situacion: "Recupere su seguridad Recordarle", activador: "un momento donde su decisión fue clave para el equipo.", desmotivacion: "Gritar desde la banda instrucciones contradictorias o emocionales.." },
      { situacion: "Transite un cambio Explicar", activador: "el \"para qué\" del cambio y cómo eso ayuda al equipo.", desmotivacion: "Moverlo de posición \"para probar\", sin darle una función clara.." }
    ],
    reseteo: `Cuando comete un error, {nombre} tiende a analizarlo mentalmente. Si no lo ayudamos a salir de ahí, puede quedarse atrapado en el "por qué fallé". Estrategia de Reseteo: Usa la lógica. En lugar de un "No pasa nada", prueba con: "El movimiento fue correcto, solo faltó un poco más de fuerza. En la próxima, ajusta eso". Al darle un dato técnico, su cerebro sale de la emoción de la frustración y vuelve a la ejecución.`,
    ecos: `En casa: Es un niño que agradece saber el "plan del día". Le gusta tener autonomía para resolver sus cosas (deberes, ordenar su cuarto) a su ritmo, siempre que sepa qué se espera de él. En la escuela: Suele ser el alumno que necesita entender el sentido de lo que estudia. Una vez que le ve la utilidad a una materia, su motor de "Impulsor" lo lleva a querer destacar en ella.`,
    checklist: {
      antes: `Repasad juntos cuál es su "misión especial" para hoy (ej: "Hoy tu misión es asegurar que los pases salgan limpios"). `,
      durante: `Evita la sobre-dirección. Confía en su proceso. Si necesita un ajuste, dáselo en el descanso con calma. `,
      despues: `Deja pasar un tiempo. Pregunta: "¿Qué decisión que tomaste hoy en el campo te hizo sentir más orgulloso?". Esto refuerza su identidad de resolutor.`,
    },
  },
  impulsor_persistente: {
    id: `impulsor_persistente`,
    eje: `D`,
    motor: `Lento`,
    label: `Impulsor Persistente`,
    perfil: `Determinación Constante y Resiliencia en el Esfuerzo`,
    bienvenida: `Este mapa es una guía para entender cómo {nombre} procesa y habita el deporte hoy. Como psicólogos de la Nave Argo, sabemos que cada niño tiene su propio compás. Este informe no busca "acelerar" a {nombre}, sino identificar las condiciones bajo las cuales su persistencia natural se convierte en su mayor fuente de disfrute. Nota de Seguridad: Los datos aquí presentados son una "fotografía del presente". El desarrollo infantil es fluido; estas tendencias describen su zona de comodidad actual para que podamos acompañarlo sin presionarlo.`,
    wow: `En la mítica Nave Argo, {nombre} sería ese tripulante que mantiene el ritmo del remo cuando los demás empiezan a flaquear por el cansancio. Su naturaleza no es la de la chispa explosiva, sino la de la llama que no se apaga. Es probable que notes que {nombre} es un niño que "va de menos a más". Su valor para el equipo es la estabilidad bajo presión. Mientras otros pueden volverse erráticos cuando el partido se pone difícil, él suele mantener su intención de logro firme. Es el "ancla de determinación" de la tripulación: alguien en quien el equipo puede confiar cuando el desafío requiere aguante y no solo velocidad. Su superpoder es la capacidad de no rendirse.`,
    motorDesc: `Técnicamente, {nombre} posee un Motor Lento. En un mundo que premia la inmediatez, es vital que como adultos reencuadremos este concepto: su motor no es "lento por falta de capacidad", es "lento por profundidad de procesamiento". Bajada humana: Su sistema nervioso necesita un tiempo de "calentamiento" más largo. Necesita sentir la resistencia del juego para que su motor se estabilice. Una vez que entra en ritmo, es muy difícil sacarlo de su foco. Acción de Sintonía: No esperes una reacción explosiva en el segundo 1 del entrenamiento. Dale permiso para entrar en calor a su ritmo; verás que su mejor versión aparece a mitad de la actividad.`,
    combustible: `El combustible de {nombre} es la superación de la resistencia. Se siente motivado cuando el desafío es difícil y requiere esfuerzo sostenido. Le gusta la sensación de "picar piedra" y ver cómo, poco a poco, logra el objetivo. Feedback de Sintonía: Valora inmensamente que reconozcas su aguante. En lugar de premiar solo el éxito rápido, prueba con: "Me impresionó cómo seguiste intentándolo con la misma fuerza hasta el final". Esto valida su identidad de persistente.`,
    grupoEspacio: `En el equipo: Se vincula a través de la lealtad y el esfuerzo compartido. Es el compañero que no abandona su posición. Su forma de cuidar al grupo es no fallar en su tarea, siendo un soporte sólido para los perfiles más volátiles. En el espacio: Se siente cómodo en contextos donde puede gestionar su propia energía. Prefiere los espacios donde el esfuerzo es predecible o donde puede imponer su propio ritmo. Los cambios bruscos de dirección o de consignas cada dos minutos pueden agotar su paciencia emocional.`,
    corazon: `Para entender a {nombre}, debemos mirar la intención detrás de su pausa: Lo que parece: A veces puede parecer falto de reacción o "pesado" en sus movimientos iniciales. Lo que realmente es (La Intención): Una búsqueda de seguridad en el esfuerzo. {nombre} no quiere desperdiciar energía; está calibrando su cuerpo para asegurarse de que puede cumplir con la misión hasta el final. Su pausa es preparación, no desinterés. El Termómetro de la Frustración: Su frustración se manifiesta como una "obstinación silenciosa". Si se siente presionado para ser más rápido de lo que su motor permite, puede llegar a bloquearse o dejar de intentar.`,
    palabrasPuente: ["Resistencia", "Paso a paso", "Constancia", "Firme", "Sigue así"],
    palabrasRuido: ["¡Rápido!", "¡Ya!", "¡Despierta!", "Dale ritmo", "No te \nquedes"],
    guia: [
      { situacion: "Mantenga su conexión Proponerle", activador: "metas de \"largo aliento\" o de resistencia.", desmotivacion: "Presionarlo para que dé una respuesta explosiva inmediata.." },
      { situacion: "Recupere su seguridad Validar", activador: "su constancia: \"Me gusta que no quitas el pie del acelerador\".", desmotivacion: "Comparar su velocidad de reacción con la de compañeros más rápidos.." },
      { situacion: "Transite un cambio Darle", activador: "tiempo de pre-aviso para que su motor se ajuste a la nueva idea.", desmotivacion: "Cambios de planes de último segundo que exijan una reacción física brusca.." }
    ],
    reseteo: `Cuando {nombre} comete un error, su tendencia es rumiarlo de forma lenta y profunda. El error se le puede quedar "pegado" durante varios minutos. Estrategia de Reseteo: No busques que se olvide del error con un chiste o una distracción. Ayúdale a convertir el error en combustible para su persistencia. Dile: "Ese paso no salió, pero tu fuerza es la que nos va a dar la siguiente oportunidad. Sigue empujando". Esto le permite integrar el fallo como parte de su proceso de esfuerzo.`,
    ecos: `En casa: Es probable que le cueste empezar las tareas (el "arranque" del motor), pero una vez que se sienta a estudiar, puede estar mucho tiempo concentrado. La clave con él es no apurarlo en el inicio, sino valorar lo que logra por persistencia. En la escuela: Es el perfil ideal para proyectos de largo plazo. Puede que no sea el que más participa en clase de forma espontánea, pero será el que entregue el trabajo más completo y madurado.`,
    checklist: {
      antes: `Asegúrate de que tenga un calentamiento físico y mental prolongado. Llegar con tiempo es vital para que su motor empiece a girar antes de que pite el árbitro. `,
      durante: `Evita los gritos de "¡Vamos, más rápido!". Sustitúyelos por gestos de aprobación que digan "Veo tu esfuerzo, mantén ese ritmo". `,
      despues: `Su charla post-partido no debe ser sobre la velocidad, sino sobre la tenacidad. Pregunta: "¿En qué momento sentiste que no te rendiste a pesar de estar cansado?".`,
    },
  },
  conector_vibrante: {
    id: `conector_vibrante`,
    eje: `I`,
    motor: `Rápido`,
    label: `Conector Vibrante`,
    perfil: `Entusiasmo Contagioso y Cohesión a través de la Energía`,
    bienvenida: `Este mapa es una invitación a mirar el deporte a través de los ojos de {nombre}. No es una sentencia sobre quién es, sino una "fotografía del presente" que nos muestra en qué condiciones fluye con más alegría. Nota de Seguridad: En Método Argo, no evaluamos el talento ni diagnosticamos la personalidad. Los niños son dinámicos; este informe simplemente nos ayuda a que el entorno deportivo sea un lugar donde {nombre} se sienta seguro, visto y motivado para seguir jugando.`,
    wow: `En el mito de la Nave Argo, {nombre} ocuparía el lugar de Orfeo: aquel que con su música y su voz marcaba el ritmo para que todos los demás remaran al unísono. Su naturaleza no es solo la de jugar, sino la de hacer que el equipo se sienta vivo. Es muy probable que notes que {nombre} es quien celebra el gol de un compañero con más fuerza que el propio, o quien busca chocar los cinco después de una jugada intensa. Su contribución a la tripulación es la cohesión emocional. Él tiene el don de elevar el ánimo del grupo cuando la energía decae. No juega solo con el balón; juega con el ánimo de quienes lo rodean. Su superpoder es transformar el esfuerzo en una fiesta compartida.`,
    motorDesc: `Técnicamente, {nombre} posee un Motor Rápido. Esto significa que su reacción ante los estímulos sociales es instantánea. Bajada humana: Para él, la comunicación no es solo palabras; es movimiento, gestos y contacto. Procesa lo que sucede en el campo de forma emocional y veloz. Si lo ves gesticulando mucho o hablando constantemente, no es falta de concentración: es su forma de mantenerse conectado al presente. Su cerebro necesita esa "retroalimentación" constante del entorno para saber que todo va bien. Acción de Sintonía: Un simple pulgar arriba o una sonrisa desde la banda viajan a la velocidad de la luz hacia su sistema. Esos pequeños gestos son los que mantienen su motor encendido.`,
    combustible: `El combustible de {nombre} es la aprobación social y la diversión grupal. Se siente vibrante cuando siente que es parte esencial de la "tribu" y cuando el ambiente es positivo. Feedback de Sintonía: Él se nutre del entusiasmo. En lugar de un feedback puramente técnico, prueba con: "¡Cómo se nota cuando estás animando, contagias a todos!". Esto valida su rol como conector y le da la seguridad necesaria para seguir intentándolo.`,
    grupoEspacio: `En el equipo: Es el "pegamento" emocional. Se vincula a través de la risa, el juego y la comunicación constante. Le afecta mucho el clima del grupo: si hay tensión o peleas, su sintonía caerá rápidamente porque su sistema prioriza el bienestar colectivo. En el espacio: Disfruta de los contextos abiertos y ruidosos. No le teme al caos del juego; al contrario, le divierte la interacción constante. Se siente cómodo en el centro de la acción, donde puede ver y ser visto por sus compañeros.`,
    corazon: `Para sintonizar con él, debemos traducir su expresividad: Lo que parece: A veces puede parecer que "se distrae" hablando o que es demasiado inquieto. Lo que realmente es (La Intención): Una necesidad de asegurar la conexión. {nombre} habla o bromea porque quiere aliviar la presión del equipo o asegurarse de que todos se lo están pasando bien. Su "distracción" es, a menudo, un intento de mantener el grupo unido. El Termómetro de la Frustración: Si se siente ignorado o si el ambiente se vuelve demasiado serio y rígido, su energía "vibrante" puede apagarse, volviéndose inusualmente callado o perdiendo el interés en la actividad.`,
    palabrasPuente: ["Juntos", "Equipo", "Vibe", "Disfruta", "¡Qué energía!", "¡Dale!"],
    palabrasRuido: ["Silencio", "Solo", "Aíslate", "Seriedad", "No hables"],
    guia: [
      { situacion: "Mantenga su conexión Permitirle", activador: "liderar el grito de equipo o el saludo inicial.", desmotivacion: "Obligarlo a realizar tareas individuales aisladas por mucho tiempo.." },
      { situacion: "Recupere su seguridad Un", activador: "gesto de complicidad (guiño, sonrisa) tras un fallo.", desmotivacion: "Críticas frías o distanciamiento emocional por parte del adulto.." },
      { situacion: "Transite un cambio Presentarlo", activador: "como una oportunidad de ayudar a otros compañeros.", desmotivacion: "Cambios de rol que lo alejen del centro de la interacción social.." }
    ],
    reseteo: `Cuando {nombre} comete un error, se preocupa por cómo lo han visto los demás. Teme "haber fallado al grupo". Estrategia de Reseteo: Usa el vínculo. Un pequeño gesto físico (mano en el hombro) o una frase que lo reconecte con sus compañeros: "¡Vuelve con ellos, te necesitan!". Esto le quita el peso del error individual y lo devuelve a su zona de confort: la misión colectiva.`,
    ecos: `En casa: Es el niño que necesita contarte todo su día nada más entrar por la puerta. Procesa su vida hablando. Escucharle con atención plena durante 10 minutos es su mejor "recarga" de batería emocional. En la escuela: Aprende mejor en trabajos grupales. Si tiene que estudiar solo, puede que le ayude "explicarle" la lección a sus muñecos o a ti; necesita que el conocimiento pase por el canal de la comunicación.`,
    checklist: {
      antes: `El objetivo debe ser la conexión (ej: "Hoy vamos a enfocarnos en lo bien que animas a tus amigos"). `,
      durante: `Déjale ser expresivo. No intentes apagar su "música". Si lo ves vibrar, es que está disfrutando. `,
      despues: `El análisis del partido debe pasar por lo social: "¿Con quién te divertiste más hoy?", "¿A quién ayudaste a sentirse mejor?".`,
    },
  },
  conector_relacional: {
    id: `conector_relacional`,
    eje: `I`,
    motor: `Medio`,
    label: `Conector Relacional`,
    perfil: `Vínculo Equilibrado y Cohesión a Ritmo Firme`,
    bienvenida: `Este mapa es una ventana para entender cómo {nombre} habita el mundo del deporte hoy. En la Nave Argo, cada ritmo es vital. Este informe no es una etiqueta definitiva, sino una "fotografía del presente" diseñada para que los adultos podamos sintonizar con su naturaleza, protegiendo siempre su disfrute y su autoestima. Nota de Seguridad: No evaluamos capacidad técnica ni salud mental. Este documento es una herramienta pedagógica para reducir la fricción y aumentar el bienestar de {nombre} en su equipo.`,
    wow: `Si la Nave Argo fuera un organismo vivo, {nombre} sería el tejido que mantiene unidos los músculos. No es el tripulante que busca destacar por encima de los demás, sino aquel que se asegura de que nadie se quede atrás. Es probable que notes que {nombre} tiene una habilidad natural para "leer" el estado de ánimo de sus compañeros. Es el puente entre los perfiles más intensos y los más reservados. Su presencia aporta una calma amable al grupo; es el compañero que busca el pase no solo por táctica, sino por inclusión. Su superpoder es la empatía operativa: la capacidad de hacer que el equipo funcione como una unidad gracias a su buena relación con todos.`,
    motorDesc: `Técnicamente, {nombre} posee un Motor Medio. Esto significa que su sistema no reacciona por puro impulso social, sino que necesita un instante para procesar el clima antes de intervenir. Bajada humana: Para él, el deporte es un evento social con reglas. No se lanza al caos sin más; observa quién está dónde y cómo se sienten sus compañeros. Si ves que tarda un momento en integrarse en un ejercicio nuevo, no es timidez, es validación. Está escaneando el entorno para asegurarse de que el vínculo con los demás es seguro antes de poner su motor en marcha. Acción de Sintonía: Dale mensajes de seguridad social. Un "estamos todos listos, vamos a divertirnos" le da la señal de que el contexto es amigable y puede empezar a actuar.`,
    combustible: `El combustible de {nombre} es la armonía grupal. Se siente vibrante cuando percibe que el equipo es un lugar seguro y que su aporte es valorado por sus pares y por el adulto. Feedback de Sintonía: Valora mucho el reconocimiento de su actitud colaborativa. En lugar de destacar solo su técnica, prueba con: "Me fijé en cómo ayudaste a tu compañero a colocarse, eso hace que el equipo sea mejor". Esto refuerza su identidad de conector y lo hace sentir esencial.`,
    grupoEspacio: `En el equipo: Se vincula a través de la lealtad y el trato cercano. Es el amigo fiel que prefiere las relaciones estables. Le afecta mucho el conflicto; una discusión entre compañeros puede hacer que baje su rendimiento porque su mente se queda intentando "reparar" el vínculo roto. En el espacio: Se siente cómodo en espacios organizados donde los roles están claros. No necesita ser siempre el centro de atención, pero sí necesita sentir que tiene un lugar físico y emocional definido en el campo.`,
    corazon: `Debemos traducir su moderación para no malinterpretarla: Lo que parece: A veces puede parecer "demasiado tranquilo" o que le falta "garra" competitiva. Lo que realmente es (La Intención): Una búsqueda de preservación del grupo. {nombre} prioriza que el juego sea fluido y agradable para todos por encima de la victoria individual. Su "falta de garra" es en realidad una elección de juego limpio y sintonía. El Termómetro de la Frustración: Su frustración es silenciosa y social. Si se siente desplazado o si el entrenador es demasiado duro con un compañero, {nombre} puede desconectarse emocionalmente como forma de protegerse del estrés ambiental.`,
    palabrasPuente: ["Colaborar", "Nosotros", "Ayuda", "Sintonía", "Fluidez", "Confianza"],
    palabrasRuido: ["Gana tú solo", "Ignóralos", "Sé agresivo", "Duro", "No \nimporta el resto"],
    guia: [
      { situacion: "Mantenga su conexión Pedirle", activador: "que ayude a integrar a alguien o que sea el \"capitán de apoyo\".", desmotivacion: "Ponerlo en situaciones de competencia directa y agresiva contra sus mejores amigos.." },
      { situacion: "Recupere su seguridad Un", activador: "mensaje de calma: \"Todo está bien, seguimos jugando juntos\".", desmotivacion: "Señalar sus errores frente al grupo (la exposición social le genera mucha ansiedad).." },
      { situacion: "Transite un cambio Explicar", activador: "cómo su nueva posición ayuda a que el equipo esté mejor equilibrado.", desmotivacion: "Cambios de equipo o de grupo sin un proceso de despedida o bienvenida.." }
    ],
    reseteo: `Cuando {nombre} comete un error, su primer pensamiento es: "¿Se habrán enfadado conmigo?". Estrategia de Reseteo: Usa la afirmación social. No necesita un análisis técnico profundo en ese instante, sino saber que el vínculo sigue intacto. Un "¡No pasa nada, seguimos contando contigo!" es el mejor botón de reinicio para su sistema.`,
    ecos: `En casa: Es un niño que valora mucho los rituales familiares (cenar juntos, un abrazo antes de dormir). Su bienestar depende de la calidad de la conexión con sus padres. En la escuela: Suele ser el mediador en los conflictos del recreo. Aprende muy bien a través de la tutoría entre pares (ayudando a otros o recibiendo ayuda de un amigo).`,
    checklist: {
      antes: `El objetivo debe ser la participación. "Hoy vamos a disfrutar de jugar con tus amigos". `,
      durante: `Evita las críticas negativas. Si necesitas corregir algo, hazlo con un tono de voz suave y privado. `,
      despues: `Valora el aspecto humano. Pregunta: "¿Cómo te sentiste hoy con el equipo?", "¿A quién sentiste que ayudaste más?".`,
    },
  },
  conector_reflexivo: {
    id: `conector_reflexivo`,
    eje: `I`,
    motor: `Lento`,
    label: `Conector Reflexivo`,
    perfil: `Cohesión Profunda y Observación del Clima Grupal`,
    bienvenida: `Este mapa es una guía para entender cómo {nombre} percibe y siente el deporte en este momento. En la Nave Argo, la fuerza no solo está en el remo, sino en la capacidad de leer el viento y el mar. Este informe es una "fotografía del presente" diseñada para que los adultos podamos sintonizar con su ritmo natural, protegiendo su bienestar y garantizando que el deporte siga siendo su lugar seguro. Nota de Seguridad: No realizamos diagnósticos ni evaluamos el rendimiento. Nuestro objetivo es pedagógico: identificar el contexto donde {nombre} fluye con menor fricción emocional para favorecer su continuidad deportiva.`,
    wow: `En la tripulación de la Nave Argo, {nombre} ocupa el lugar de quien detecta las corrientes invisibles. Es el tripulante que no necesita gritar para ser escuchado, porque su valor reside en su capacidad para entender lo que el equipo necesita antes de que los demás se den cuenta. Es probable que notes que {nombre} es un niño que observa mucho antes de participar plenamente. Su contribución a la tripulación es la cohesión desde la calma. Él no busca ser el centro de atención, sino el "pegamento silencioso" que hace que todos se sientan parte de algo más grande. Su superpoder es la sabiduría social: la capacidad de percibir quién está triste, quién está solo o cuándo el equipo ha perdido la sintonía, aportando una presencia equilibrada que suaviza las tensiones.`,
    motorDesc: `Técnicamente, {nombre} posee un Motor Lento. En un contexto deportivo que suele exigir velocidad inmediata, es crucial entender que su ritmo no es falta de energía, sino exceso de procesamiento. Bajada humana: Para él, entrar en el juego es como entrar en una conversación profunda: necesita escuchar primero para saber qué decir después. Su cerebro escanea el clima emocional y las posiciones antes de activar sus músculos. Si parece "lento" al arrancar, es porque está integrando toda la información del entorno. Acción de Sintonía: Dale tiempo de "aterrizaje". No lo lances a la acción sin un previo aviso. Permitirle observar los primeros 5 minutos del entrenamiento le ayuda a que su motor se sincronice con el ritmo del grupo.`,
    combustible: `El combustible de {nombre} es la aceptación y la pertenencia genuina. No le motiva ganar por ganar, sino la sensación de que es parte de un grupo donde se le aprecia por quien es. Feedback de Sintonía: Valora mucho el feedback privado y afectuoso. Un "vi cómo te alegraste por el pase de tu compañero, me gusta que estés atento a ellos" es mucho más potente para él que un aplauso público que lo ponga en el centro de todas las miradas.`,
    grupoEspacio: `En el equipo: Se vincula a través de la empatía y el tiempo compartido. Prefiere las conversaciones uno a uno o los grupos pequeños donde el ruido emocional es bajo. Le afectan profundamente las injusticias o los gritos, incluso si no son dirigidos hacia él, porque su sistema es un receptor del clima grupal. En el espacio: Se siente cómodo en zonas donde puede tener una visión global. A menudo prefiere posiciones que le permitan ver todo el campo, ya que eso le da la seguridad de entender la "historia" de lo que está pasando en el juego.`,
    corazon: `Debemos traducir su pausa para no juzgarla como desinterés: Lo que parece: A veces puede parecer distraído, tímido o que "le falta intensidad". Lo que realmente es (La Intención): Una búsqueda de seguridad emocional. {nombre} no quiere cometer un error que rompa la armonía del equipo. Su pausa es un acto de respeto por el juego y por los demás. El Termómetro de la Frustración: Su frustración se manifiesta como un "repliegue". Si el ambiente se vuelve hostil o demasiado competitivo, se encerrará en sí mismo y dejará de participar activamente para proteger su equilibrio interno.`,
    palabrasPuente: ["Observa", "Siente", "Juntos", "A tu ritmo", "Tranquilo", "Pertenencia"],
    palabrasRuido: ["¡Muévete!", "¡Reacciona!", "¿Qué estás mirando?", "Sé más agresivo", "¡Ya, ya!"],
    guia: [
      { situacion: "Mantenga su conexión Permitirle", activador: "un rol de observación o de apoyo a un compañero nuevo.", desmotivacion: "Ponerlo en el centro de una competencia individual y eliminatoria.." },
      { situacion: "Recupere su seguridad Un", activador: "mensaje de voz baja: \"Tómate tu tiempo, yo estoy aquí contigo\".", desmotivacion: "Exponer sus dudas o silencios como una falla frente a los demás.." },
      { situacion: "Transite un cambio Introducir", activador: "los cambios de forma gradual, explicándole el lado humano (ej: \"tu amigo te necesita en esta zona\").", desmotivacion: "Cambios bruscos de equipo que lo separen de sus referentes afectivos de golpe.." }
    ],
    reseteo: `Cuando {nombre} comete un error, su sistema tiende a "congelarse" emocionalmente. Se siente desconectado del grupo por el fallo. Estrategia de Reseteo: Dale una salida que use su fortaleza: la observación. Dile: "No te preocupes por esa jugada, ahora fíjate cómo se mueven ellos para que en la próxima sepas dónde estar". Esto le da una tarea de procesamiento que lo saca de la emoción negativa y lo devuelve al juego desde su zona de confort: el análisis del clima.`,
    ecos: `En casa: Es el niño que necesita "tiempo de descompresión" al llegar de la escuela. No le preguntes "¿cómo te fue?" nada más entrar; deja que su motor baje de revoluciones y él mismo vendrá a contarte las cosas cuando se sienta sintonizado. En la escuela: Suele ser un excelente compañero, alguien que escucha y que prefiere los ambientes de aprendizaje tranquilos. Puede que necesite más tiempo para entregar tareas creativas porque les pone mucha carga emocional y detalle.`,
    checklist: {
      antes: `Llegad con tiempo extra para que pueda ver el ambiente. El caos de llegar tarde desajusta su motor de Conector Reflexivo para todo el partido. `,
      durante: `Evita las correcciones en voz alta. Tu presencia silenciosa y un gesto de aprobación ocasional son suficientes. `,
      despues: `Valora el bienestar. Pregunta: "¿Cómo te sentiste hoy con tus amigos?", "¿Hubo algún momento que te hiciera sonreír?".`,
    },
  },
  sosten_agil: {
    id: `sosten_agil`,
    eje: `S`,
    motor: `Rápido`,
    label: `Sostén Ágil`,
    perfil: `Reacción de Auxilio Veloz y Apoyo Dinámico`,
    bienvenida: `Este mapa nos permite entender cómo {nombre} elige habitar el deporte hoy. En la Nave Argo, la seguridad de la travesía depende de quienes aseguran que cada pieza esté en su sitio. Este informe no es una etiqueta fija, sino una "fotografía del presente" diseñada para que los adultos podamos sintonizar con su naturaleza, protegiendo su autoestima y su ganas de seguir jugando. Nota de Seguridad: No evaluamos talento ni realizamos diagnósticos. Nuestro objetivo es identificar el contexto donde {nombre} fluye con mayor comodidad y menor estrés.`,
    wow: `En el mito de los Argonautas, {nombre} sería ese tripulante atento que, mientras todos miran hacia el horizonte, él detecta una pequeña fisura en el casco y la repara al instante. Su naturaleza es la de la protección activa. Es probable que notes que {nombre} tiene un "radar" especial para detectar cuándo un compañero necesita ayuda o cuándo ha quedado un espacio vacío en el campo. Su contribución a la tripulación es la seguridad reactiva: él no busca el protagonismo del gol, sino la satisfacción de saber que "el equipo está a salvo" gracias a su intervención. Su superpoder es la omnipresencia de apoyo: estar donde se le necesita, justo en el momento en que se le necesita.`,
    motorDesc: `Técnicamente, {nombre} posee un Motor Rápido. Pero a diferencia de otros perfiles rápidos que usan esa velocidad para atacar, él la usa para asistir. Bajada humana: Su sistema nervioso está en "alerta amable". Su velocidad de reacción se activa ante la necesidad externa. Si un balón queda suelto o un compañero pierde su posición, su cuerpo responde de forma casi instintiva. No necesita pensar mucho la jugada; su inteligencia es de auxilio inmediato. Acción de Sintonía: Valora su capacidad de estar atento. Un "qué bien cubriste ese espacio" le confirma que su motor rápido está cumpliendo su misión de proteger al grupo.`,
    combustible: `El combustible de {nombre} es sentirse útil y necesario. Se siente vibrante cuando percibe que su esfuerzo silencioso ha evitado un problema para el equipo. Su motivación es extrínseca y relacional: "juego para que mi equipo esté bien". Feedback de Sintonía: Él se nutre de la validación del esfuerzo invisible. En lugar de pedirle que "brille solo", prueba con: "Hoy fuiste el motor que mantuvo a todos seguros, sin ti el equipo no habría estado tan ordenado". Esto refuerza su identidad de sostén.`,
    grupoEspacio: `En el equipo: Es el compañero que siempre tiene un gesto de ayuda. Es probable que sea quien recoja los materiales sin que se lo pidan o quien ayude a un compañero a atarse los cordones. Se vincula a través del servicio. En el espacio: Se siente cómodo en posiciones de cobertura. Le gusta tener el juego de frente para poder identificar dónde hace falta su ayuda. Los espacios vacíos no le asustan, los ve como "misiones de auxilio" que debe cumplir.`,
    corazon: `Para sintonizar con él, debemos traducir su tendencia a quedarse en un segundo plano: Lo que parece: A veces puede parecer que "no quiere ser el protagonista" o que le falta ambición individual. Lo que realmente es (La Intención): Un alto sentido de la responsabilidad colectiva. {nombre} siente que si él deja su puesto de apoyo para ir a buscar el brillo personal, el equipo quedará vulnerable. Su "falta de ambición" es en realidad una entrega total al bienestar del grupo. El Termómetro de la Frustración: Su frustración aparece cuando siente que su ayuda no es valorada o cuando el ambiente es tan caótico que no sabe a quién ayudar primero. Ahí puede sentirse abrumado y perder su eficacia.`,
    palabrasPuente: ["Apoyo", "Asegura", "Ayuda", "Suma", "Equilibrio", "Te \n\nnecesitamos ahí"],
    palabrasRuido: ["Tú solo", "Olvídate del resto", "Brilla", "Sé el \n\nprotagonista", "Ignora a tu compañero"],
    guia: [
      { situacion: "Mantenga su conexión Darle", activador: "una \"misión de apoyo\" específica (ej: \"Tu rol es ayudar a que la defensa esté tranquila\").", desmotivacion: "Dejarlo en una posición donde no tenga a nadie a quien ayudar o asistir.." },
      { situacion: "Recupere su seguridad Validar", activador: "su trabajo \"sucio\" o invisible: \"Vi ese cruce que hiciste, fue clave\".", desmotivacion: "Exigirle que tome riesgos individuales excesivos que dejen al equipo expuesto.." },
      { situacion: "Transite un cambio Explicar", activador: "cómo su nueva función es vital para la seguridad de la Nave.", desmotivacion: "Hacer cambios que él perciba como una \"falta de confianza\" en su capacidad de ayuda.." }
    ],
    reseteo: `Cuando {nombre} comete un error, se siente mal porque siente que "le ha fallado al equipo". Estrategia de Reseteo: No le pidas que se olvide. Dale una nueva tarea de ayuda. Dile: "Esa no salió, pero ahora tu compañero te necesita para cubrir esta zona, ¡ve a ayudarlo!". Al poner su motor rápido al servicio de otro, su sistema nervioso "limpia" el error propio y recupera la sintonía de inmediato.`,
    ecos: `En casa: Es el hijo que reacciona rápido cuando ve que necesitas ayuda con las bolsas de la compra o poniendo la mesa. Valora mucho que le des "misiones de ayuda" en casa; le hace sentirse parte importante de la familia. En la escuela: Suele ser el compañero que presta los lápices o ayuda a explicar algo a quien no entendió. Se siente seguro en roles de tutoría o asistencia.`,
    checklist: {
      antes: `El objetivo debe ser la asistencia (ej: "Hoy vamos a enfocarnos en lo atento que estás para ayudar a tus compañeros"). `,
      durante: `Evita pedirle que "se lance al ataque" de forma agresiva si eso implica abandonar su rol de sostén. Valora su posicionamiento. `,
      despues: `La charla debe centrarse en su valor como equipo: "¿A quién sentiste que ayudaste más hoy?", "¿En qué momento sentiste que el equipo estuvo seguro gracias a ti?".`,
    },
  },
  sosten_confiable: {
    id: `sosten_confiable`,
    eje: `S`,
    motor: `Medio`,
    label: `Sostén Confiable`,
    perfil: `Consistencia Serena y Apoyo Estructurado`,
    bienvenida: `Este mapa es una guía para comprender cómo {nombre} elige habitar el deporte hoy. En la Nave Argo, la seguridad del viaje no solo depende de la velocidad, sino de la solidez de quienes mantienen el rumbo sin flaquear. Este informe es una "fotografía del presente" diseñada para que los adultos podamos sintonizar con su ritmo, protegiendo su bienestar y garantizando que el deporte sea su lugar de confianza. Nota de Seguridad: No evaluamos talento ni realizamos diagnósticos de salud mental. Nuestro objetivo es pedagógico: identificar el contexto donde {nombre} fluye con mayor comodidad para evitar el estrés innecesario.`,
    wow: `En el mito de los Argonautas, {nombre} sería ese tripulante que asegura que cada cabo esté bien atado y que el ritmo del remo sea constante, sin importar si el mar está calmo o picado. Su naturaleza es la de la presencia incondicional. Es probable que notes que {nombre} no es el niño que busca los focos ni el que hace las jugadas más vistosas, pero es quien nunca falla en su posición. Su contribución a la tripulación es la fiabilidad absoluta: él es el "seguro de vida" del equipo. Su valor no reside en la sorpresa, sino en la repetición de lo que funciona. Su superpoder es la estabilidad emocional: la capacidad de mantener la calma y el orden cuando los demás empiezan a perder los nervios.`,
    motorDesc: `Técnicamente, {nombre} posee un Motor Medio. Esto se traduce en un procesamiento equilibrado: no es impulsivo ni es excesivamente lento; es rítmico. Bajada humana: Su sistema nervioso prefiere la previsibilidad. Necesita entender la secuencia de lo que va a pasar para poner su motor en marcha. Si el entrenamiento sigue una estructura clara, {nombre} rinde al máximo. Los cambios bruscos de planes o los ejercicios "caóticos" pueden desajustar su sincronía, no por falta de capacidad, sino porque su cerebro está diseñado para la eficiencia técnica y el orden. Acción de Sintonía: Anticípale lo que va a pasar. "Primero haremos esto y luego aquello". Esa pequeña estructura le da la seguridad necesaria para que su motor medio funcione como un reloj.`,
    combustible: `El combustible de {nombre} es la competencia y el deber cumplido. Se siente motivado cuando sabe exactamente qué se espera de él y logra realizarlo de forma correcta. No busca el aplauso masivo, sino la satisfacción interna de "haber hecho su parte". Feedback de Sintonía: Valora mucho el reconocimiento de su consistencia. En lugar de pedirle que haga algo "increíble", prueba con: "Me da mucha seguridad verte en el campo porque siempre estás donde tienes que estar". Esto valida su identidad de sostén confiable.`,
    grupoEspacio: `En el equipo: Se vincula a través de la lealtad y el respeto a las normas. Es el compañero que respeta los turnos y que sigue las instrucciones del entrenador al pie de la letra. Evita los conflictos y suele ser una figura conciliadora que aporta "normalidad" al grupo. En el espacio: Se siente cómodo en zonas bien definidas. Le gusta tener una "parcela" de responsabilidad clara en el campo. Si sabe que "esta es su zona", la defenderá con una tenacidad admirable. El desorden espacial (todos corriendo tras el balón) le genera una fatiga mental mayor que a otros perfiles.`,
    corazon: `Para sintonizar con él, debemos valorar su moderación: Lo que parece: A veces puede parecer que "no se arriesga" o que es demasiado conservador en su juego. Lo que realmente es (La Intención): Un deseo profundo de preservar la seguridad del equipo. {nombre} siente que arriesgar innecesariamente es poner en peligro el equilibrio del grupo. Su "falta de riesgo" es en realidad una gestión responsable del juego. El Termómetro de la Frustración: Su frustración es sorda. Si el ambiente se vuelve demasiado errático o si las reglas no se cumplen, puede empezar a mostrarse apático o desmotivado, simplemente porque el entorno ha dejado de ser "lógico" para él.`,
    palabrasPuente: ["Constante", "Seguro", "Orden", "Cumplir", "Paso a \n\npaso", "Confianza"],
    palabrasRuido: ["¡Sorprende!", "¡Improvisa!", "Cambio de planes", "Haz \nlo que quieras", "Rápido, rápido"],
    guia: [
      { situacion: "Mantenga su conexión Darle", activador: "una función clara y estable (ej: \"Tu tarea hoy es asegurar esta posición\").", desmotivacion: "Cambiarle de posición o de tarea cada 5 minutos sin explicación.." },
      { situacion: "Recupere su seguridad Validar", activador: "su fiabilidad: \"Hiciste exactamente lo que el equipo necesitaba\".", desmotivacion: "Presionarlo para que sea \"creativo\" o \"explosivo\" de forma forzada.." },
      { situacion: "Transite un cambio Explicar", activador: "el cambio con lógica y antelación: \"A partir de ahora, vamos a probar esto para...\".", desmotivacion: "Modificaciones abruptas de última hora en el equipo o en las reglas.." }
    ],
    reseteo: `Cuando {nombre} comete un error, se siente desajustado porque "se salió del plan". Estrategia de Reseteo: Devuélvele la estructura. No busques una reacción emocional, busca una técnica. Dile: "No pasa nada, vuelve a tu posición y recuerda el paso 1 y el paso 2". Al recordarle el procedimiento, su cerebro vuelve a sentir que tiene el control y su motor medio recupera la sintonía.`,
    ecos: `En casa: Es un niño que agradece las rutinas. Saber qué se va a cenar o qué haremos el fin de semana le da mucha paz mental. Es el hijo en el que "puedes confiar" para que cumpla con sus pequeñas responsabilidades diarias sin tener que recordárselo constantemente. En la escuela: Suele ser un alumno metódico. Le va muy bien en materias que tienen procesos claros y lógica. Prefiere los exámenes donde sabe exactamente qué temas van a caer a las pruebas de "creatividad abierta".`,
    checklist: {
      antes: `Mantén la rutina previa al partido (mismo horario, misma bolsa). La previsibilidad es su mejor calentamiento mental. `,
      durante: `Evita las correcciones emocionales. Si necesitas ajustar algo, dáselo como un dato técnico concreto. `,
      despues: `Valora la consistencia. Pregunta: "¿En qué momento sentiste que tenías todo bajo control?", "¿Te sentiste cómodo siguiendo el plan del equipo?".`,
    },
  },
  sosten_sereno: {
    id: `sosten_sereno`,
    eje: `S`,
    motor: `Lento`,
    label: `Sostén Sereno`,
    perfil: `Resistencia Imperturbable y Calma Estructural`,
    bienvenida: `Este mapa es una guía para comprender cómo {nombre} elige habitar el deporte hoy. En la Nave Argo, la seguridad de la misión depende de quienes mantienen la calma cuando el resto de la tripulación entra en pánico. Este informe es una "fotografía del presente" diseñada para que los adultos podamos sintonizar con su ritmo, protegiendo su bienestar y garantizando que el deporte sea su refugio de confianza. Nota de Seguridad: No evaluamos talento ni realizamos diagnósticos de salud mental. Nuestro objetivo es pedagógico: identificar el contexto donde {nombre} fluye con mayor comodidad para evitar el estrés innecesario y fomentar su disfrute.`,
    wow: `En el mito de los Argonautas, {nombre} sería ese tripulante que, en medio de la niebla más espesa, permanece sentado en su sitio, manteniendo el ritmo del remo con una paz que tranquiliza a todos los demás. Su naturaleza es la de la estabilidad profunda. Es probable que notes que {nombre} es el niño que parece "no sentir la presión". Mientras otros se aceleran o se frustran a gritos, él mantiene su expresión y su ritmo. Su contribución a la tripulación es la calma estructural: él es el ancla emocional del equipo. Su valor no reside en la velocidad de su ataque, sino en su capacidad para no desordenarse nunca. Su superpoder es la imperturbabilidad: ser el lugar seguro al que sus compañeros pueden mirar cuando el partido se vuelve caótico.`,
    motorDesc: `Técnicamente, {nombre} posee un Motor Lento. Es fundamental que como adultos entendamos que este ritmo es su mayor defensa: su sistema nervioso procesa la información a una profundidad que requiere tiempo, pero que una vez activada, es imparable. Bajada humana: Su motor funciona por inercia. Le cuesta el arranque inicial y los cambios de ritmo repentinos, pero una vez que coge su "velocidad de crucero", puede mantenerla durante horas sin fatigarse mentalmente. Si parece que no reacciona ante un grito de "¡corre!", no es desobediencia; es que su motor está diseñado para la resistencia, no para la explosividad. Acción de Sintonía: No intentes acelerar su proceso de "arranque". Dale los primeros minutos del partido para que su sistema se asiente. Verás que su mejor versión aparece cuando el cansancio empieza a afectar a los demás, pero él sigue como si nada.`,
    combustible: `El combustible de {nombre} es la paz y el sentido de pertenencia. Se siente vibrante cuando el ambiente es predecible, amable y estable. Le motiva saber que su presencia ayuda a que el equipo esté tranquilo. Feedback de Sintonía: Valora mucho el reconocimiento de su temple. En lugar de pedirle que sea "más agresivo", prueba con: "Me encanta la tranquilidad que transmites al equipo, nos ayudas a todos a pensar mejor". Esto valida su identidad de sostén sereno.`,
    grupoEspacio: `En el equipo: Se vincula a través de la lealtad silenciosa. Es el compañero que no busca conflictos y que siempre está disponible para un amigo. Su forma de cuidar al grupo es estar presente. Es probable que sea el niño que todos quieren tener cerca cuando las cosas van mal, porque su calma es contagiosa. En el espacio: Se siente cómodo en posiciones de retaguardia o de apoyo. Le gusta tener el panorama completo frente a sus ojos. El caos de jugadores amontonados le resulta estresante; él prefiere las zonas donde puede mantener su estructura y su orden técnico sin interferencias.`,
    corazon: `Para sintonizar con él, debemos entender qué hay detrás de su ritmo pausado: Lo que parece: A veces puede parecer pasivo, que "le faltan ganas" o que no está conectado con la intensidad del partido. Lo que realmente es (La Intención): Una búsqueda de preservación del equilibrio. {nombre} siente que la sobre-excitación es un error. Su pausa es una forma de asegurar que cada movimiento que haga sea sólido y seguro. Su "falta de intensidad" es en realidad una economía de esfuerzo estratégica. El Termómetro de la Frustración: Su frustración es casi invisible. Si se siente excesivamente presionado para actuar rápido, simplemente se "desconectará". Dejará de participar no por enfado, sino por saturación sensorial.`,
    palabrasPuente: ["Tranquilo", "A tu ritmo", "Firme", "Sólido", "Confío en \n\ntu calma", "Paso a paso"],
    palabrasRuido: ["¡Rápido!", "¡Explota!", "¡Despierta!", "Dale ritmo", "¡Ya!"],
    guia: [
      { situacion: "Mantenga su conexión Darle", activador: "un rol de \"organizador de la calma\" o de último recurso de seguridad.", desmotivacion: "Someterlo a una presión constante de \"velocidad\" o resultados inmediatos.." },
      { situacion: "Recupere su seguridad Validar", activador: "su imperturbabilidad: \"Qué bien mantuviste tu sitio a pesar del lío\".", desmotivacion: "Gritarle para que \"reaccione\" ante una jugada fallida.." },
      { situacion: "Transite un cambio Explicar", activador: "el cambio con mucha antelación y suavidad, apelando a la seguridad del equipo.", desmotivacion: "Cambios de posición \"sorpresa\" o de última hora que rompan su inercia de juego.." }
    ],
    reseteo: `Cuando {nombre} comete un error, su sistema no entra en pánico, pero puede "ralentizarse" aún más. Estrategia de Reseteo: No busques una reacción rápida. Dale un gesto de calma. Un simple "Seguimos igual, confío en ti" es suficiente. Su cerebro necesita sentir que el error no ha destruido la estabilidad del entorno para volver a poner su motor en marcha.`,
    ecos: `En casa: Es el hijo que aporta paz. No suele ser el que genera conflictos, pero necesita sus tiempos de silencio. Valora mucho que no se le apure por la mañana para ir al colegio; necesita un despertar suave para que su motor empiece a girar con sintonía. En la escuela: Es el alumno que no se bloquea en los exámenes difíciles. Puede que tarde más en terminar, pero su nivel de precisión suele ser alto debido a su procesamiento profundo.`,
    checklist: {
      antes: `Asegura un ambiente tranquilo. Evita las prisas y los gritos de ánimo excesivamente ruidosos antes de salir de casa. `,
      durante: `Observa su lenguaje corporal. Si lo ves demasiado estático, no le pidas velocidad; pídele un "objetivo de posición" pequeño. `,
      despues: `Valora su resistencia. Pregunta: "¿Cómo lograste mantener la calma cuando todos corrían?", "¿Te sentiste cómodo ayudando a que el equipo estuviera tranquilo?".`,
    },
  },
  estratega_reactivo: {
    id: `estratega_reactivo`,
    eje: `C`,
    motor: `Rápido`,
    label: `Estratega Reactivo`,
    perfil: `Precisión Instantánea y Ajuste Táctico Veloz`,
    bienvenida: `Este mapa es una brújula para entender cómo {nombre} procesa el deporte hoy. En la Nave Argo, la victoria depende de quienes saben leer las estrellas y ajustar las velas al segundo. Este informe es una "fotografía del presente" diseñada para que los adultos acompañemos su naturaleza analítica, protegiendo su autoestima y asegurando que su búsqueda de la perfección sea una fuente de disfrute. Nota de Seguridad: Este no es un diagnóstico clínico. Es una herramienta pedagógica para identificar el contexto donde {nombre} fluye con menor fricción emocional.`,
    wow: `En el mito de los Argonautas, {nombre} sería Tifis, el timonel capaz de detectar una roca sumergida mucho antes que los demás. Su naturaleza es la de la vigilancia técnica. Es probable que notes que {nombre} es el primero en darse cuenta si un compañero está mal ubicado o si una regla no se está cumpliendo. Su contribución a la tripulación es la corrección preventiva: él no busca el balón por impulso, sino para poner orden. Su superpoder es la agudeza diagnóstica: la capacidad de procesar la táctica a una velocidad asombrosa, convirtiéndose en el "ojo del entrenador" dentro del campo.`,
    motorDesc: `Técnicamente, {nombre} posee un Motor Rápido. En su caso, la rapidez no es física (correr más), sino mental. Bajada humana: Su cerebro es como un escáner que funciona a mil revoluciones. Detecta patrones, errores y oportunidades de forma casi inmediata. Si lo ves señalando o dando instrucciones rápidas a sus compañeros, no es que quiera mandar, es que su motor procesa el "deber ser" del juego tan rápido que siente la necesidad de comunicarlo para que el equipo funcione mejor. Acción de Sintonía: Valora su lectura. Un "qué buena visión tuviste ahí" le confirma que su motor de estratega está cumpliendo su misión de dar claridad al grupo.`,
    combustible: `El combustible de {nombre} es la precisión y el orden. Se siente vibrante cuando el plan sale "limpio" y cuando siente que su conocimiento de las reglas ayuda al equipo. Le motiva la sensación de "hacer las cosas bien". Feedback de Sintonía: Él se nutre del feedback lógico. En lugar de un "¡Bien hecho!", prueba con: "Esa corrección de posición que hiciste fue exacta para recuperar el balón". Esto valida su proceso de pensamiento y lo hace sentir competente.`,
    grupoEspacio: `En el equipo: Se vincula a través de la instrucción y la norma. Es el compañero que recuerda las reglas y el que espera que todos cumplan su parte. Su lealtad se demuestra asegurando que el equipo no cometa errores evitables. En el espacio: Se siente cómodo en posiciones de visión periférica. Le gusta estar donde pueda "ver el tablero" completo. El caos absoluto o la falta de consignas claras le generan un estrés motor inmediato; él necesita que el espacio tenga una lógica.`,
    corazon: `Para sintonizar con él, debemos traducir su "exigencia": Lo que parece: A veces puede parecer un niño "sabelotodo" o que critica demasiado a sus compañeros. Lo que realmente es (La Intención): Un deseo de excelencia colectiva. {nombre} no critica por maldad; sufre si el equipo pierde el orden porque siente que así son más vulnerables. Su intención es proteger el éxito del grupo a través del orden. El Termómetro de la Frustración: Su frustración es reactiva y técnica. Si el árbitro se equivoca o un compañero ignora una instrucción obvia, su motor rápido puede saltar en forma de protesta o de un gesto de "brazos caídos".`,
    palabrasPuente: ["Precisión", "Lógica", "Analiza", "Ajuste", "Táctica", "Fíjate en..."],
    palabrasRuido: ["Como sea", "No importa la regla", "Tira y ya", "Olvida \nel plan", "No pienses tanto"],
    guia: [
      { situacion: "Mantenga su conexión Darle", activador: "una \"misión de ajuste\" (ej: \"Ayúdanos a que la defensa no pierda la línea\").", desmotivacion: "Consignas ambiguas o entrenamientos basados solo en el azar.." },
      { situacion: "Recupere su seguridad Validar", activador: "su lógica: \"Tienes razón en lo que viste, ahora veamos cómo comunicarlo mejor\".", desmotivacion: "Ridiculizar su obsesión por las reglas o el orden.." },
      { situacion: "Transite un cambio Explicar", activador: "la lógica técnica detrás del cambio de posición o de grupo.", desmotivacion: "Cambios de planes sin una explicación coherente que él pueda procesar.." }
    ],
    reseteo: `Cuando {nombre} comete un error, su motor rápido entra en "bucle de análisis": se queda pensando en qué falló técnicamente. Estrategia de Reseteo: Dale un nuevo dato táctico. No le digas "ya pasó". Dile: "Analizaste bien, pero el viento cambió la trayectoria. En la próxima, ajusta un metro a la izquierda". Al darle una solución técnica, su mente "cierra" el error y vuelve al presente con una misión clara.`,
    ecos: `En casa: Es el hijo que te recordará si te saltaste un paso de una receta o si es hora de irse. Valora mucho que seas coherente con las normas que pones. En la escuela: Suele destacar en matemáticas o ciencias, donde hay una "respuesta correcta" y una lógica que seguir. Puede frustrarse si el profesor es desorganizado.`,
    checklist: {
      antes: `Repasad el "objetivo táctico" del día. Saber qué tiene que observar le da mucha seguridad. `,
      durante: `Evita los gritos emocionales. Usa señales breves que apelen a su visión del campo (ej: "¡Escanea el espacio!"). `,
      despues: `La charla debe ser de "ajuste técnico". Pregunta: "¿Qué fue lo más interesante que notaste hoy en la defensa del otro equipo?".`,
    },
  },
  estratega_analitico: {
    id: `estratega_analitico`,
    eje: `C`,
    motor: `Medio`,
    label: `Estratega Analítico`,
    perfil: `Procesamiento Técnico y Ejecución con Propósito`,
    bienvenida: `Este mapa es una ventana para comprender cómo {nombre} procesa y habita el deporte hoy. En la Nave Argo, el éxito de la misión no solo depende de la fuerza, sino de la exactitud de los cálculos. Este informe es una "fotografía del presente" diseñada para que los adultos podamos sintonizar con su ritmo analítico, protegiendo su autoestima y garantizando que el deporte sea un espacio de aprendizaje y disfrute. Nota de Seguridad: No evaluamos talento ni realizamos diagnósticos. Nuestro objetivo es pedagógico: identificar el contexto donde {nombre} fluye con mayor comodidad y menor estrés.`,
    wow: `En el mito de los Argonautas, {nombre} sería ese tripulante que estudia las estrellas y los mapas antes de que la nave zarpe. Su naturaleza es la de la preparación inteligente. Es probable que notes que {nombre} es un niño que valora profundamente las instrucciones. Su contribución a la tripulación es la calidad en la ejecución: él no busca ser el más rápido ni el más ruidoso, sino el más preciso. Su valor reside en su capacidad para seguir el plan de juego con una fidelidad que aporta orden a todo el equipo. Su "superpoder" es la atención al detalle: la capacidad de notar esos pequeños ajustes técnicos que hacen que una jugada pase de "buena" a "perfecta".`,
    motorDesc: `Técnicamente, {nombre} posee un Motor Medio. Esto significa que su sistema prefiere procesar la información antes de activar la respuesta física. Bajada humana: Para él, el deporte es un problema que hay que resolver correctamente. No "tira el balón" por tirar; su cerebro evalúa la posición, la fuerza y la dirección. Si a veces parece que se toma un segundo extra, no es duda, es calibración. Una vez que su motor medio procesa la instrucción y la encuentra lógica, su ejecución suele ser de las más limpias del grupo. Acción de Sintonía: Dale tiempo para "masticar" la nueva táctica. Verás que después de ver el ejercicio un par de veces, lo realizará con una precisión que sorprenderá a todos.`,
    combustible: `El combustible de {nombre} es la competencia técnica y la claridad. Se siente vibrante cuando entiende el "por qué" de las cosas y cuando logra realizar un movimiento tal como se lo explicaron. Le motiva el dominio de la técnica. Feedback de Sintonía: Él se nutre del feedback específico. En lugar de un "¡Bien hecho!", prueba con: "Me fijé en cómo pusiste el pie para ese pase, fue técnicamente perfecto". Esto valida su proceso mental y su esfuerzo por la precisión.`,
    grupoEspacio: `En el equipo: Se vincula a través de la tarea compartida. Respeta mucho a los compañeros que se esfuerzan por jugar bien y que siguen las reglas. No suele buscar el liderazgo emocional, pero es una referencia táctica para los demás: "si quieres saber cómo se hace este ejercicio, mira a {nombre}". En el espacio: Se siente cómodo en entornos estructurados. Le gusta saber cuáles son los límites del campo y cuál es su posición exacta. El desorden o los entrenamientos donde "todo vale" le generan una fatiga mental invisible porque su cerebro intenta encontrar un orden donde no lo hay.`,
    corazon: `Para sintonizar con él, debemos entender qué hay detrás de su seriedad: Lo que parece: A veces puede parecer un niño algo rígido, serio o que le cuesta "soltarse" y ser espontáneo. Lo que realmente es (La Intención): Un deseo de no fallar al equipo. {nombre} se toma el juego con responsabilidad porque siente que su precisión es su forma de ayudar. Su "rigidez" es en realidad concentración y respeto por el deporte. El Termómetro de la Frustración: Su frustración es interna y técnica. Si no logra realizar un movimiento como él sabe que debe hacerse, puede mostrarse muy autocrítico o silencioso. Teme el desajuste técnico más que el resultado del marcador.`,
    palabrasPuente: ["Técnica", "Precisión", "Plan", "Lógica", "Ajuste", "Cómo"],
    palabrasRuido: ["Como salga", "Improvisa", "No pienses", "¡Ya, ya!", "Olvida la técnica"],
    guia: [
      { situacion: "Mantenga su conexión Proponerle", activador: "retos de precisión (ej: \"Hoy el objetivo es que 4 de cada 5 pases lleguen al destino\").", desmotivacion: "Entrenamientos caóticos o basados solo en el contacto físico sin táctica.." },
      { situacion: "Recupere su seguridad Validar", activador: "la calidad de su proceso: \"Vi cómo pensaste la jugada, la lógica era perfecta\".", desmotivacion: "Críticas genéricas o comparaciones con niños que juegan de forma más impulsiva.." },
      { situacion: "Transite un cambio Explicar", activador: "detalladamente las nuevas reglas y el sentido del cambio de posición.", desmotivacion: "Cambios de planes de último segundo que rompan su mapa mental del juego.." }
    ],
    reseteo: `Cuando {nombre} comete un error, su sistema entra en "modo análisis técnico". Estrategia de Reseteo: Usa la lógica. No le pidas que se olvide. Dile: "El análisis fue bueno, pero la ejecución falló por X detalle. En la próxima, ajusta esto". Al darle un dato técnico para corregir, su mente "cierra" el error y vuelve al presente con una misión de mejora clara.`,
    ecos: `En casa: Es el hijo que prefiere saber el "por qué" de las normas. Valora mucho que seas coherente y que los planes se cumplan. Le gusta tener su espacio y sus materiales ordenados a su manera. En la escuela: Suele ser un alumno muy cumplidor que disfruta de las materias con procesos claros (matemáticas, gramática, música). Necesita saber qué se espera exactamente de él en un examen para no sentirse ansioso.`,
    checklist: {
      antes: `Asegúrate de que sepa el horario y el lugar con antelación. La previsibilidad es su mejor calentamiento mental. `,
      durante: `Evita las correcciones constantes. Confía en su capacidad de auto-ajuste; él ya sabe cuándo ha fallado técnicamente. `,
      despues: `La charla debe ser sobre la inteligencia del juego. Pregunta: "¿Qué fue lo que más te gustó de cómo funcionó hoy la táctica del equipo?".`,
    },
  },
  estratega_observador: {
    id: `estratega_observador`,
    eje: `C`,
    motor: `Lento`,
    label: `Estratega Observador`,
    perfil: `Análisis Profundo del Entorno y Precisión Lógica`,
    bienvenida: `Este mapa es una invitación a descubrir cómo {nombre} procesa el mundo del deporte hoy. En la Nave Argo, el éxito no solo dependía de la fuerza de los remeros, sino de la capacidad del vigía para leer las corrientes invisibles. Este informe es una "fotografía del presente" diseñada para que los adultos sintonicen con su ritmo analítico, protegiendo su autoestima y asegurando que su inteligencia sea su mayor fuente de disfrute. Nota de Seguridad: No evaluamos talento ni realizamos diagnósticos. Nuestro objetivo es pedagógico: identificar el contexto donde {nombre} fluye con menor fricción emocional para que nunca quiera dejar de jugar.`,
    wow: `En el mito de los Argonautas, {nombre} sería aquel que permanece en silencio observando el horizonte, detectando patrones que los demás ignoran por la prisa. Su naturaleza es la de la comprensión integral. Es muy probable que notes que {nombre} es un niño que "mira el partido incluso cuando está dentro de él". Su contribución a la tripulación es la claridad estratégica: él no corre tras el balón por instinto, sino que busca entender hacia dónde se dirige la jugada. Su superpoder es la visión periférica mental: la capacidad de procesar la lógica del juego desde una calma imperturbable, convirtiéndose en el ancla inteligente del equipo.`,
    motorDesc: `Técnicamente, {nombre} posee un Motor Lento. En un entorno deportivo que a menudo grita "¡rápido!", es vital entender que su motor no es lento por falta de capacidad, sino por exceso de datos. Bajada humana: Su cerebro es un procesador de alta fidelidad. Antes de mover un músculo, está analizando la posición del rival, el espacio disponible y la mejor opción técnica. Su "pausa" inicial no es duda, es recaudación de información. Una vez que tiene la certeza de qué debe hacer, su ejecución suele ser asombrosamente precisa. Acción de Sintonía: Permítele ser el observador. Si le das un par de minutos para mirar cómo otros hacen un ejercicio nuevo, su motor se sintonizará mucho mejor que si lo obligas a ser el primero en probar.`,
    combustible: `El combustible de {nombre} es el entendimiento. Se siente vibrante cuando logra descifrar cómo funciona el juego del equipo contrario o cuando una estrategia que él previó se cumple. Le motiva la sensación de "tener el control mental" de la situación. Feedback de Sintonía: Valora el feedback intelectual. En lugar de elogios genéricos, prueba con: "Me di cuenta de cómo estabas observando al defensa antes de dar ese pase; tu lectura fue excelente". Esto valida su identidad de estratega.`,
    grupoEspacio: `En el equipo: Se vincula a través del respeto técnico y la calma. No suele ser el que más grita, pero es a quien sus compañeros miran cuando necesitan orden. Su lealtad se demuestra manteniendo su posición y cumpliendo el plan con una disciplina impecable. En el espacio: Se siente cómodo en zonas que le permitan ver el campo completo. Prefiere tener espacio a su alrededor para poder pensar. El contacto físico excesivo o el "amontonamiento" de jugadores le genera una fatiga mental inmediata porque le impide leer el juego con claridad.`,
    corazon: `Para sintonizar con él, debemos traducir su silencio: Lo que parece: A veces puede parecer distraído, tímido o que "no tiene sangre" ante la intensidad del partido. Lo que realmente es (La Intención): Un deseo de actuar con lógica. {nombre} se niega a actuar de forma caótica o por puro impulso. Su pausa es un acto de respeto por la eficiencia. Para él, moverse sin sentido es peor que no moverse. El Termómetro de la Frustración: Su frustración es una "parálisis por análisis". Si el juego se vuelve demasiado caótico o irracional, puede retraerse y dejar de participar porque su mente no encuentra un patrón que seguir.`,
    palabrasPuente: ["Analiza", "Fíjate", "Qué ves", "Tómate tu tiempo", "Lógica", "Precisión"],
    palabrasRuido: ["¡No pienses!", "¡Reacciona ya!", "¡Corre como sea!", "Olvida el plan", "¡Muévete!"],
    guia: [
      { situacion: "Mantenga su conexión Darle", activador: "una \"misión de lectura\": \"Fíjate por dónde están atacando más\".", desmotivacion: "Pedirle que sea \"agresivo\" o \"explosivo\" de forma constante y sin motivo táctico.." },
      { situacion: "Recupere su seguridad Validar", activador: "su lectura: \"Qué buena visión tuviste del campo hoy\".", desmotivacion: "Exponerlo o criticarlo frente al grupo por su tiempo de reacción pausado.." },
      { situacion: "Transite un cambio Explicar", activador: "detalladamente la lógica y las nuevas reglas de la posición.", desmotivacion: "Cambios de planes repentinos que rompan su mapa mental del juego.." }
    ],
    reseteo: `Cuando {nombre} comete un error, su mente se queda "atrapada" analizando la falla para que no vuelva a ocurrir. Estrategia de Reseteo: Dale un ancla técnica. No le digas "ya pasó". Dile: "Analizaste bien el pase, solo faltó ajustar la dirección por el viento. Ahora, vuelve a observar el centro". Al darle un dato nuevo para procesar, su mente sale del bucle del error y vuelve al presente.`,
    ecos: `En casa: Es un hijo que necesita entender el "por qué" de las cosas. No acepta un "porque sí". Valora mucho los juegos de estrategia, los puzzles o cualquier actividad que requiera pensar un plan. En la escuela: Suele ser ese alumno que parece estar en su mundo, pero que cuando le preguntas, tiene la respuesta más profunda. Le encantan las ciencias, el ajedrez o la lectura, donde puede sumergirse en sistemas lógicos.`,
    checklist: {
      antes: `Llegad con tiempo. {nombre} necesita observar el campo, el clima y el ambiente para sentirse seguro antes de empezar. `,
      durante: `Utiliza un tono de voz calmado. Evita las correcciones constantes; confía en su proceso interno de ajuste. `,
      despues: `Conversad sobre la táctica. Pregunta: "¿Qué fue lo más interesante que notaste hoy en el otro equipo?". Esto valida su identidad y refuerza su pasión por el aspecto inteligente del deporte.`,
    },
  },
};

export function getArchetypeByEjeMotor(eje: string, motor: string): ArchetypeData | null {
  return Object.values(ARCHETYPE_DATA).find(a => a.eje === eje && a.motor === motor) ?? null;
}