// Portuguese (Brazilian) translations for Argo Method archetype content

export interface ArchetypeTranslation {
  label: string;
  perfil: string;
  perfilExtended: string;
  bienvenida: string;
  wow: string;
  motorDesc: string;
  combustible: string;
  grupoEspacio: string;
  corazon: string;
  palabrasPuente: string[];
  palabrasRuido: string[];
  guia: { situacion: string; activador: string; desmotivacion: string }[];
  reseteo: string;
  ecos: string;
  checklist: { antes: string; durante: string; despues: string };
}

export interface TendenciaTranslation {
  parrafo: string;
  palabrasPuenteExtra: string[];
  palabrasRuidoExtra: string[];
}

export const ARCHETYPE_DATA_PT: Record<string, ArchetypeTranslation> = {
  impulsor_dinamico: {
    label: `Impulsor Dinâmico`,
    perfil: `Ação Direta e Resolução Imediata`,
    perfilExtended: `Move-se antes que a maioria termina de processar a situação. Tende a precisar sentir que suas ações produzem um impacto visível para se manter motivado e conectado. Nos momentos de maior inércia do time, costuma ser quem ativa o movimento.`,
    bienvenida: `Este mapa é um convite para nos aproximarmos da maneira como {nombre} tende a viver e sentir o esporte hoje. Assim como um mapa de navegação não qualifica o terreno como "bom" ou "ruim", mas sugere qual equipamento levar para percorrê-lo com prazer, este relatório oferece pistas para que a experiência esportiva seja um espaço de alegria e não de pressão. Nota importante: Este relatório não avalia o talento nem prediz o futuro esportivo. Seus achados são probabilísticos e dinâmicos: descrevem tendências atuais que muito provavelmente evoluirão junto com a maturação natural de {nombre}. Não são traços fixos, mas uma fotografia de sua sintonia presente.`,
    wow: `No mito da nave Argo, cada tripulante tinha uma natureza única. {nombre} tende a ocupar naturalmente o lugar de quem ativa o movimento. É provável que não seja alguém que espere as coisas acontecerem; sua maneira de estar no mundo parece projetada para ser a faísca que inicia a ação. É provável que você perceba que {nombre} tende a ser aquele tripulante que, nos momentos de maior dúvida ou quando o jogo para, toma a iniciativa para reiniciar o avanço. Sua contribuição não é apenas física, é uma energia de resolução que tende a impulsionar toda a tripulação para frente. Não busca liderar pelo simples ato de liderar, mas porque sua natureza parece sentir que o movimento é o estado onde o time se sente mais seguro. Sua grande força tende a ser a coragem de decidir no instante.`,
    motorDesc: `O perfil de {nombre} se associa a um ritmo naturalmente ágil. No cotidiano, isso sugere que a distância entre sua percepção e sua ação tende a ser muito curta. Aprender, para {nombre}, provavelmente significa experimentar. É possível que não precise que expliquem a teoria do passe num quadro durante dez minutos; sua maneira de processar a informação parece funcionar melhor quando seu corpo está em movimento. Se você notar inquietação durante as conversas técnicas, é provável que não seja falta de interesse nem de respeito, mas seu ritmo interno dizendo: "Já entendi a ideia, agora me deixa tentar o como". Convite de sintonia: Quando quiser compartilhar uma indicação, tente fazê-lo enquanto {nombre} tem a bola ou está em movimento. A informação tende a "viajar" melhor em seu sistema quando seu corpo está ativo.`,
    combustible: `O que faz {nombre} querer voltar no próximo domingo? Seu combustível principal tende a ser o sentido de progresso e o impacto. É provável que precise sentir que suas ações produzem uma mudança visível no jogo. Sente-se vibrante quando pode dizer: "Eu fiz isso acontecer". Feedback de sintonia: {nombre} tende a ser muito sensível ao reconhecimento de sua iniciativa. É provável que valorize mais ouvir "Adorei como você se animou a tentar aquele passe" do que um simples "Muito bem jogado". O elogio que nutre sua confiança é aquele que valida sua coragem, não apenas o resultado.`,
    grupoEspacio: `No time: {nombre} tende a se vincular por meio da ação compartilhada. Sua forma de ser "amigo" dos companheiros provavelmente seja passar a bola ou defender uma posição exigente. Sua lealdade costuma se demonstrar no esforço físico conjunto mais do que nas palavras. No espaço: Tende a preferir cenários de alta intensidade e espaços dinâmicos. Gosta do "vai e vem". Os exercícios estáticos ou as filas longas para esperar sua vez costumam ser sua maior fonte de fricção emocional; é aí onde sua sintonia tende a cair e pode aparecer a distração.`,
    corazon: `Para sintonizar com {nombre}, é valioso aprender a traduzir o que vemos: O que pode parecer: Impaciência ou vontade de "querer fazer tudo sozinho". O que provavelmente é (A Intenção): Um desejo profundo de dissolver a incerteza. Quando o jogo fica caótico, {nombre} tende a sentir que precisa agir rápido para que o time não perca o rumo. Seu impulso costuma ser um ato de cuidado com a missão do time. O termômetro emocional: Sua frustração tende a se expressar "para fora". Se você notar gestos bruscos ou um aumento de velocidade de forma errática, é provável que seja um sinal de que seu sistema superaqueceu. Não é "mau humor"; é saturação de intensidade.`,
    palabrasPuente: ["Impacto", "Iniciativa", "Você decide", "Avança", "Resolução"],
    palabrasRuido: ["Espera sem fazer nada", "Fica quieto", "Isso não é pra você", "Deixa outro fazer", "Não opine"],
    guia: [
      { situacion: "Manter sua conexão", activador: "Oferecer uma responsabilidade clara e com impacto (ex: \"Seu papel é ativar a pressão na saída\").", desmotivacion: "Consignas vagas ou passivas que não lhe deem um propósito visível dentro do jogo." },
      { situacion: "Acompanhar sua confiança", activador: "Validar uma decisão específica que tomou, mesmo que o resultado não tenha sido perfeito.", desmotivacion: "Apontamentos baseados na emoção do momento ou comparações com outros." },
      { situacion: "Facilitar uma mudança de papel", activador: "Explicar o sentido estratégico da mudança (ex: \"Preciso de você aqui para cobrir esse espaço-chave\").", desmotivacion: "Fazer mudanças sem uma breve explicação que dê sentido à sua nova posição." }
    ],
    reseteo: `Quando {nombre} comete um erro, sua tendência pode ser canalizar a frustração por meio da intensidade física. Acompanhamento sugerido: Provavelmente não é o melhor momento para parar o fluxo e explicar o aspecto técnico. Seu ritmo ágil tende a precisar "limpar" a sensação com uma nova ação bem-sucedida. Oferecer um objetivo pequeno e alcançável de imediato (ex: "Bom intento! Agora, busca esse passe") pode permitir que volte emocionalmente ao jogo sem ficar ancorado na culpa.`,
    ecos: `Embora este relatório nasça do esporte, essas tendências de ritmo provavelmente fazem parte de sua maneira de processar o mundo: Em casa: É provável que prefira instruções uma de cada vez. Se receber três indicações juntas, seu ritmo ágil tenderá a se ativar com a primeira e a soltar as outras duas. Na escola: Seu estilo de aprendizagem tende a ser o "fazer". Os projetos práticos ou os experimentos onde pode ver resultados imediatos costumam ser sua zona de maior entusiasmo e prazer.`,
    checklist: {
      antes: `Combinar juntos um único objetivo baseado em sua intenção (ex: "Hoje o objetivo é que você se divirta buscando espaços").`,
      durante: `Praticar o Silêncio Aliado. Confiar em sua capacidade de resolver. Sua presença tranquila tende a ser o melhor apoio.`,
      despues: `Respeitar os 20 minutos de resfriamento. Deixar que seu ritmo baixe de intensidade antes de conversar sobre o jogo. Começar sempre perguntando: "O que foi o que mais te divertiu hoje?".`,
    },
  },

  impulsor_decidido: {
    label: `Impulsor Decidido`,
    perfil: `Iniciativa Estratégica e Execução com Propósito`,
    perfilExtended: `Combina o impulso de agir com a clareza de saber para onde vai. Tende a tomar a iniciativa quando o objetivo está definido, com uma força e foco que transformam a intenção em resultados tangíveis. Sua força está na consistência da execução, não na impulsividade.`,
    bienvenida: `Este mapa é um convite para entender como {nombre} se conecta com o esporte nesta fase de sua vida. Não é uma definição de sua personalidade para sempre, mas uma "fotografia do presente" que nos ajuda a afinar nossa comunicação. Nota de segurança: Este relatório não avalia o talento. Seu único fim é que {nombre} se sinta compreendido e desfrute mais de cada partida, reduzindo a fricção emocional entre suas necessidades e nossas expectativas.`,
    wow: `Na tripulação da Nave Argo, {nombre} tende a ser quem garante que o avanço seja firme e com direção. Não parece ser o tripulante que pula na água sem olhar, mas aquele que, uma vez que entende para onde vão, coloca toda a sua determinação para que a nave chegue ao destino. É provável que você perceba que {nombre} mostra uma confiança muito alta quando o plano está claro. Seu valor para o grupo tende a residir em sua consistência: uma vez que decide que é o momento de agir, costuma fazê-lo com uma força e um foco admiráveis. Não busca a ação pelo barulho, mas pela conquista. Sua presença no time tende a trazer segurança na execução; é quem provavelmente transforma a intenção em resultados tangíveis.`,
    motorDesc: `O perfil de {nombre} se associa a um ritmo naturalmente equilibrado. Isso sugere que seu sistema prefere um ritmo de "processar para executar". Diferente dos perfis que agem por puro instinto, {nombre} tende a ter um breve tempo de análise interna. Costuma observar a jogada, avaliar suas opções e então agir com decisão. Um olhar mais próximo: Se às vezes parece que demora um instante a mais para começar, é provável que não seja falta de vontade, mas sua maneira de garantir que a ação seja a adequada. Convite de sintonia: Em vez de pedir que "seja mais rápido" de forma genérica, dar clareza sobre o objetivo pode fazer com que seu ritmo natural flua com mais leveza ao se sentir seguro.`,
    combustible: `O que motiva {nombre}? Seu combustível tende a ser a eficácia. É provável que goste de sentir que é competente e que suas ações fazem sentido dentro do jogo. Feedback de sintonia: Tende a valorizar muito que você reconheça a qualidade de sua decisão. Em vez de dizer "Que gol!", tente: "Gostei muito de como você esperou o momento certo para chutar". Isso valida seu processo mental e reforça sua confiança.`,
    grupoEspacio: `No time: {nombre} tende a se vincular por meio da colaboração orientada a tarefas. É provável que se sinta à vontade com companheiros que respeitam seu espaço e que cumprem com sua parte do plano. Não é necessariamente o que mais fala no vestiário, mas tende a ser quem lidera pelo exemplo quando a bola começa a rolar. No espaço: Costuma preferir os contextos onde há certa ordem tática. Sente-se à vontade em sua zona atribuída e flui melhor quando o campo não está em caos total. A desordem excessiva ou a falta de regras claras em um exercício podem frustrá-lo e apagar sua iniciativa.`,
    corazon: `Para sintonizar com {nombre}, é valioso olhar além do comportamento: O que pode parecer: Às vezes pode dar a impressão de ser teimoso ou muito sério. O que provavelmente é (A Intenção): Um desejo de fazer bem. {nombre} tende a ter um alto nível de autoexigência. Se se mostra firme, é provável que esteja tentando manter o rumo da situação para garantir o resultado para seu time. O termômetro emocional: Sua frustração costuma ser silenciosa no início, mas pode se notar numa "tensão física" aumentada. Se começa a jogar com muita força, é provável que seja um sinal de que precisa que você devolva a calma com uma indicação clara e lógica.`,
    palabrasPuente: ["Estratégia", "Objetivo", "Você sabe como", "Passo a passo", "Efetivo"],
    palabrasRuido: ["Do jeito que der", "Improvisa sem pensar", "Não planeje", "Não pense", "Vai fundo sem mais"],
    guia: [
      { situacion: "Manter sua conexão", activador: "Oferecer um objetivo técnico que convide a usar sua potência e decisão.", desmotivacion: "Mudar as regras do jogo no meio do treino sem aviso." },
      { situacion: "Acompanhar sua confiança", activador: "Lembrar um momento em que sua decisão foi fundamental para o time.", desmotivacion: "Indicações contraditórias ou emocionais gritadas da beira do campo." },
      { situacion: "Facilitar uma mudança", activador: "Explicar o \"para que\" da mudança e como isso fortalece o time.", desmotivacion: "Movê-lo de posição \"para testar\", sem lhe dar uma função clara." }
    ],
    reseteo: `Quando comete um erro, {nombre} tende a analisá-lo mentalmente. Se não o acompanharmos para sair desse circuito, pode ficar preso no "por que não funcionou". Acompanhamento sugerido: Usar a lógica. Em vez de um "Não tem problema", tentar: "O movimento estava correto, só faltou um pouco mais de força. Na próxima, ajuste isso". Ao oferecer um dado técnico, sua mente tende a sair da emoção da frustração e voltar à execução.`,
    ecos: `Em casa: {nombre} tende a agradecer saber o "plano do dia". É provável que valorize ter autonomia para resolver suas coisas (tarefas, arrumar o quarto) em seu ritmo, desde que as expectativas estejam claras. Na escola: Costuma precisar entender o sentido do que estuda. Uma vez que percebe a utilidade de uma disciplina, seu impulso natural tende a gerar vontade de se destacar nela.`,
    checklist: {
      antes: `Revisar juntos qual é sua "missão especial" para hoje (ex: "Hoje sua missão é garantir que os passes saiam limpos").`,
      durante: `Evitar a super-direção. Confiar em seu processo. Se precisar de um ajuste, ofereça-o no descanso com calma.`,
      despues: `Deixar passar um tempo. Perguntar: "Qual decisão que você tomou hoje em campo te fez se sentir mais orgulhoso?". Isso reforça sua identidade como resolutor.`,
    },
  },

  impulsor_persistente: {
    label: `Impulsor Persistente`,
    perfil: `Determinação Constante e Resiliência no Esforço`,
    perfilExtended: `Sua força não é a velocidade, mas a permanência. Tende a sustentar o esforço quando outros param, com uma determinação que cresce quanto mais difícil fica o caminho. O time pode contar com sua vontade nos momentos que exigem resistência mais do que velocidade.`,
    bienvenida: `Este mapa é um convite para entender como {nombre} processa e habita o esporte hoje. Na Nave Argo sabemos que cada esportista tem seu próprio compasso. Este relatório não busca "acelerar" {nombre}, mas identificar as condições sob as quais sua persistência natural se torna sua maior fonte de prazer. Nota de segurança: Os dados aqui apresentados são uma "fotografia do presente". O desenvolvimento infantil é fluido; essas tendências descrevem sua zona de conforto atual para que possamos acompanhar sem pressionar.`,
    wow: `Na mítica Nave Argo, {nombre} tende a ser aquele tripulante que mantém o ritmo do remo quando os demais começam a fraquejar pelo cansaço. Sua natureza não parece ser a da faísca explosiva, mas a da chama que não se apaga. É provável que você perceba que {nombre} tende a "ir de menos a mais". Seu valor para o time costuma ser a estabilidade sob pressão. Enquanto outros podem ficar erráticos quando a partida fica difícil, {nombre} tende a manter sua intenção de conquista firme. É a "âncora de determinação" da tripulação: alguém em quem o time pode confiar quando o desafio exige resistência e não apenas velocidade. Sua grande força tende a ser a capacidade de não desistir.`,
    motorDesc: `O perfil de {nombre} se associa a um ritmo naturalmente profundo. Num mundo que premia a imediatez, é valioso que como adultos enquadremos esse conceito de outra forma: seu ritmo não sugere "falta de capacidade", mas profundidade de processamento. Um olhar mais próximo: Seu sistema nervioso parece precisar de um tempo de "aquecimento" mais prolongado. Precisa sentir a textura do jogo para que seu ritmo se estabilize. Uma vez que entra em sintonia, costuma ser muito difícil tirá-lo de seu foco. Convite de sintonia: Não esperar uma reação explosiva no primeiro minuto do treino. Dar-lhe permissão para entrar em ritmo em seu próprio tempo; é provável que sua melhor versão apareça no meio da atividade.`,
    combustible: `O combustível de {nombre} tende a ser a superação da resistência. É provável que se sinta motivado quando o desafio é exigente e requer esforço sustentado. Gosta da sensação de ir construindo aos poucos até ver como conquista o objetivo. Feedback de sintonia: Tende a valorizar imensamente que você reconheça sua resistência. Em vez de premiar apenas o sucesso rápido, tentar: "Me impressionou como você continuou tentando com a mesma força até o final". Isso valida sua identidade como persistente.`,
    grupoEspacio: `No time: Tende a se vincular por meio da lealdade e do esforço compartilhado. É provável que seja o companheiro que não abandona sua posição. Sua forma de cuidar do grupo costuma ser não falhar em sua tarefa, sendo um suporte sólido para os perfis mais voláteis. No espaço: Tende a se sentir à vontade em contextos onde pode gerenciar sua própria energia. Costuma preferir os espaços onde o esforço é previsível ou onde pode impor seu próprio ritmo. As mudanças bruscas de direção ou de consignas a cada dois minutos podem esgotar sua paciência emocional.`,
    corazon: `Para entender {nombre}, é valioso olhar a intenção por trás de sua pausa: O que pode parecer: Às vezes pode dar a impressão de que demora para reagir ou que seus movimentos iniciais são pausados. O que provavelmente é (A Intenção): Uma busca de segurança no esforço. {nombre} tende a não querer desperdiçar energia; parece estar calibrando seu corpo para garantir que pode cumprir com a missão até o final. Sua pausa costuma ser preparação, não desinteresse. O termômetro emocional: Sua frustração pode se manifestar como uma "pausa de resguardo" — um recuo protetor onde simplesmente para de responder ao ritmo do entorno. Se se sentir pressionado para agir mais rápido do que seu ritmo permite, pode chegar a parar completamente.`,
    palabrasPuente: ["Resistência", "Passo a passo", "Constância", "Firme", "Continua assim"],
    palabrasRuido: ["Se apresse sem pensar", "Reaja já!", "Não fique pensando", "Dê mais velocidade", "Todos já fizeram"],
    guia: [
      { situacion: "Manter sua conexão", activador: "Propor metas de \"longo fôlego\" ou de resistência.", desmotivacion: "Pressioná-lo para que dê uma resposta explosiva imediata." },
      { situacion: "Acompanhar sua confiança", activador: "Validar sua constância: \"Gosto de como você mantém o esforço sem parar\".", desmotivacion: "Comparar sua velocidade de reação com a de companheiros de ritmo diferente." },
      { situacion: "Facilitar uma mudança", activador: "Dar tempo de pré-aviso para que seu ritmo se ajuste à nova proposta.", desmotivacion: "Mudanças de planos de última hora que exijam uma reação física brusca." }
    ],
    reseteo: `Quando {nombre} comete um erro, sua tendência pode ser processá-lo de forma profunda e sustentada. O erro pode ficar "grudado" durante vários minutos. Acompanhamento sugerido: Não tentar que esqueça com uma piada ou uma distração. Ajudá-lo a converter a experiência em combustível para sua persistência. Dizer-lhe: "Esse passo não saiu, mas sua força é o que vai nos dar a próxima oportunidade. Continua empurrando". Isso pode permitir que integre o ocorrido como parte de seu processo de esforço.`,
    ecos: `Em casa: É provável que tenha dificuldade para começar as tarefas (o "arranque" de seu ritmo), mas uma vez que se sentar para estudar, pode ficar muito tempo concentrado. A chave tende a ser não apressar no início, mas valorizar o que conquista pela persistência. Na escola: Costuma ser o perfil ideal para projetos de longo prazo. Pode não ser o que mais participa em sala de forma espontânea, mas é provável que seja quem entrega o trabalho mais completo e amadurecido.`,
    checklist: {
      antes: `Garantir um aquecimento físico e mental prolongado. Chegar com tempo é valioso para que seu ritmo comece a se ativar antes do apito do árbitro.`,
      durante: `Substituir as exigências de velocidade por gestos de aprovação que digam "Vejo seu esforço, mantenha esse ritmo".`,
      despues: `A conversa posterior não deveria se centrar na velocidade, mas na tenacidade. Perguntar: "Em que momento sentiu que não desistiu apesar de estar cansado?".`,
    },
  },

  conector_vibrante: {
    label: `Conector Vibrante`,
    perfil: `Entusiasmo Contagiante e Coesão pela Energia`,
    perfilExtended: `Sua presença ativa o entorno de forma quase imediata. Tende a ser quem eleva o ânimo do grupo quando a energia cai, celebrando a conquista de um companheiro com mais força do que a própria. Sua contribuição mais valiosa costuma ser o clima emocional que cria ao seu redor.`,
    bienvenida: `Este mapa é um convite para olhar o esporte pelos olhos de {nombre}. Não é uma sentença sobre quem é, mas uma "fotografia do presente" que nos mostra em quais condições tende a fluir com mais alegria. Nota de segurança: No Método Argo não avaliamos o talento nem diagnosticamos a personalidade. O desenvolvimento infantil é dinâmico; este relatório simplesmente nos ajuda a fazer com que o entorno esportivo seja um lugar onde {nombre} se sinta seguro, visto e motivado para continuar jogando.`,
    wow: `No mito da Nave Argo, {nombre} tende a ocupar o lugar de Orfeu: aquele que com sua música e sua voz marcava o ritmo para que todos os demais remassem ao mesmo tempo. Sua natureza não parece ser apenas a de jogar, mas a de fazer o time se sentir vivo. É muito provável que você perceba que {nombre} tende a ser quem celebra o gol de um companheiro com mais força do que o próprio, ou quem busca dar um toque de mãos depois de uma jogada intensa. Sua contribuição à tripulação costuma ser a coesão emocional. Tende a ter o dom de elevar o ânimo do grupo quando a energia cai. Não joga apenas com a bola; joga com o ânimo de quem o rodeia. Sua grande força tende a ser transformar o esforço em uma festa compartilhada.`,
    motorDesc: `O perfil de {nombre} se associa a um ritmo naturalmente ágil. Isso sugere que sua reação ante os estímulos sociais tende a ser instantânea. Um olhar mais próximo: A comunicação para {nombre} provavelmente não seja apenas palavras; é movimento, gestos e contato. Parece processar o que acontece em campo de forma emocional e veloz. Se você notar muita gesticulação ou comunicação constante, é provável que não seja falta de concentração: é sua forma de permanecer conectado ao presente. Sua maneira de estar parece precisar dessa "retroalimentação" constante do entorno para saber que tudo vai bem. Convite de sintonia: Um simples joinha ou um sorriso da beira do campo viajam na velocidade da luz até seu sistema. Esses pequenos gestos tendem a ser os que mantêm seu ritmo aceso.`,
    combustible: `O combustível de {nombre} tende a ser a aprovação social e a diversão em grupo. É provável que se sinta vibrante quando sente que é parte essencial da "tribo" e quando o ambiente é positivo. Feedback de sintonia: Tende a se nutrir do entusiasmo. Em vez de um feedback puramente técnico, tentar: "Como se nota quando você está animando, contagia a todos!". Isso valida seu papel como conector e lhe dá a segurança para continuar tentando.`,
    grupoEspacio: `No time: Tende a ser o "cola" emocional. Vincula-se por meio do riso, do jogo e da comunicação constante. O clima do grupo o afeta muito: se há tensão ou brigas, sua sintonia pode cair rapidamente porque seu sistema tende a priorizar o bem-estar coletivo. No espaço: Costuma desfrutar dos contextos abertos e barulhentos. Não teme o caos do jogo; ao contrário, se diverte com a interação constante. Tende a se sentir à vontade no centro da ação, onde pode ver e ser visto pelos seus companheiros.`,
    corazon: `Para sintonizar com {nombre}, é valioso traduzir sua expressividade: O que pode parecer: Às vezes pode dar a impressão de que "se distrai" falando ou que é muito agitado. O que provavelmente é (A Intenção): Uma necessidade de garantir a conexão. {nombre} tende a falar ou brincar porque quer aliviar a pressão do time ou garantir que todos estejam se divertindo. Sua "distração" costuma ser, muitas vezes, uma tentativa de manter o grupo unido. O termômetro emocional: Se se sentir invisível ou se o ambiente ficar muito sério e estrito, sua energia "vibrante" pode se apagar, tornando-se inusitadamente calado ou perdendo o interesse na atividade.`,
    palabrasPuente: ["Juntos", "Time", "Energia", "Aproveita", "Que energia!", "Vai!"],
    palabrasRuido: ["Não fale com ninguém", "Faz isso sozinho", "Se isola", "Para de comemorar", "Não se relacione"],
    guia: [
      { situacion: "Manter sua conexão", activador: "Convidá-lo a liderar o grito do time ou a saudação inicial.", desmotivacion: "Mantê-lo em tarefas individuais isoladas por muito tempo." },
      { situacion: "Acompanhar sua confiança", activador: "Um gesto de cumplicidade (piscada, sorriso) depois de um tropeço.", desmotivacion: "Distanciamento emocional ou frieza da parte do adulto." },
      { situacion: "Facilitar uma mudança", activador: "Apresentá-la como uma oportunidade de acompanhar outros companheiros.", desmotivacion: "Mudanças de papel que o afastem do centro da interação social." }
    ],
    reseteo: `Quando {nombre} comete um erro, tende a se preocupar com como os outros o viram. Pode temer "ter falhado com o grupo". Acompanhamento sugerido: Usar o vínculo. Um pequeno gesto físico (mão no ombro) ou uma frase que o reconecte com seus companheiros: "Volta com eles, eles precisam de você!". Isso pode tirar o peso do erro individual e devolvê-lo à sua zona de conforto: a missão coletiva.`,
    ecos: `Em casa: Costuma precisar te contar tudo sobre seu dia assim que chega em casa. Provavelmente processa sua vida falando. Escutar com atenção plena durante 10 minutos costuma ser a melhor "recarga" de bateria emocional. Na escola: Tende a aprender melhor em trabalhos em grupo. Se precisar estudar sozinho, pode ajudar "explicar" a lição em voz alta para seus brinquedos ou para você; é provável que precise que o conhecimento passe pelo canal da comunicação.`,
    checklist: {
      antes: `O objetivo pode girar em torno da conexão (ex: "Hoje vamos nos concentrar em como você anima seus amigos").`,
      durante: `Deixar que seja expressivo. Não tentar apagar sua "música". Se notar que vibra, é provável que esteja se divertindo.`,
      despues: `A análise da partida pode passar pelo social: "Com quem você se divertiu mais hoje?", "A quem você acompanhou quando precisava?".`,
    },
  },

  conector_relacional: {
    label: `Conector Relacional`,
    perfil: `Vínculo Equilibrado e Coesão a Ritmo Firme`,
    perfilExtended: `Sabe quando animar e quando escutar, e essa leitura tende a fazê-la de forma intuitiva. Sua habilidade para ler o estado de ânimo de seus companheiros o torna a ponte entre os perfis mais intensos e os mais reservados. Sua presença traz calma e coesão sem tirar a alegria do grupo.`,
    bienvenida: `Este mapa é uma janela para entender como {nombre} habita o mundo do esporte hoje. Na Nave Argo, cada ritmo é vital. Este relatório não é uma etiqueta definitiva, mas uma "fotografia do presente" criada para que os adultos possamos sintonizar com sua natureza, protegendo sempre seu prazer e sua autoestima. Nota de segurança: Não avaliamos capacidade técnica nem saúde mental. Este documento é uma ferramenta para reduzir a fricção e aumentar o bem-estar de {nombre} em seu time.`,
    wow: `Se a Nave Argo fosse um organismo vivo, {nombre} tende a ser o tecido que mantém unidos os músculos. Não parece ser o tripulante que busca se destacar acima dos demais, mas aquele que garante que ninguém fique para trás. É provável que você perceba que {nombre} tem uma habilidade natural para "ler" o estado de ânimo de seus companheiros. Tende a ser a ponte entre os perfis mais intensos e os mais reservados. Sua presença costuma trazer uma calma amável ao grupo; é provável que seja o companheiro que busca o passe não apenas por tática, mas por inclusão. Sua grande força tende a ser a empatia operativa: a capacidade de fazer o time funcionar como uma unidade graças ao seu bom relacionamento com todos.`,
    motorDesc: `O perfil de {nombre} se associa a um ritmo naturalmente equilibrado. Isso sugere que seu sistema não reage por puro impulso social, mas tende a precisar de um instante para processar o clima antes de intervir. Um olhar mais próximo: O esporte provavelmente seja um evento social com regras. Não se lança ao caos sem mais; tende a observar quem está onde e como se sentem seus companheiros. Se você vir que demora um momento para se integrar em um exercício novo, é provável que não seja timidez, mas validação. Parece estar escaneando o entorno para garantir que o vínculo com os demais é seguro antes de colocar seu ritmo em marcha. Convite de sintonia: Dar-lhe mensagens de segurança social. Um "estamos todos prontos, vamos nos divertir" pode dar-lhe o sinal de que o contexto é amigável e que pode começar a agir.`,
    combustible: `O combustível de {nombre} tende a ser a harmonia grupal. É provável que se sinta vibrante quando percebe que o time é um lugar seguro e que sua contribuição é valorizada por seus pares e pelo adulto. Feedback de sintonia: Tende a valorizar muito o reconhecimento de sua atitude colaborativa. Em vez de destacar apenas sua técnica, tentar: "Percebi como você acompanhou seu companheiro na posição, isso faz o time melhor". Isso reforça sua identidade de conector e o faz se sentir essencial.`,
    grupoEspacio: `No time: Tende a se vincular por meio da lealdade e do trato próximo. É provável que seja o amigo fiel que prefere as relações estáveis. O conflito o afeta muito; uma discussão entre companheiros pode fazer seu rendimento cair porque sua mente tende a ficar tentando "reparar" o vínculo afetado. No espaço: Costuma se sentir à vontade em espaços organizados onde os papéis estão claros. Não precisa ser sempre o centro das atenções, mas tende a precisar sentir que tem um lugar físico e emocional definido em campo.`,
    corazon: `É valioso traduzir sua moderação para não interpretá-la mal: O que pode parecer: Às vezes pode dar a impressão de ser "muito tranquilo" ou que lhe falta intensidade competitiva. O que provavelmente é (A Intenção): Uma busca de preservação do grupo. {nombre} tende a priorizar que o jogo seja fluido e agradável para todos acima da vitória individual. Sua aparente "falta de garra" costuma ser na verdade uma escolha de jogo limpo e sintonia. O termômetro emocional: Sua frustração tende a ser silenciosa e social. Se se sentir deslocado ou se o adulto for duro demais com um companheiro, {nombre} pode se desconectar emocionalmente como forma de se proteger do estresse ambiental.`,
    palabrasPuente: ["Colaborar", "Nós", "Acompanhar", "Sintonia", "Fluidez", "Confiança"],
    palabrasRuido: ["Ganha você sozinho", "Não presta atenção neles", "Esqueça o grupo", "Seja mais intenso", "O que acontece com os outros não importa"],
    guia: [
      { situacion: "Manter sua conexão", activador: "Convidá-lo a integrar alguém ou a ser o \"capitão de apoio\".", desmotivacion: "Colocá-lo em situações de competição direta e intensa contra seus amigos mais próximos." },
      { situacion: "Acompanhar sua confiança", activador: "Uma mensagem de calma: \"Tudo está bem, seguimos jogando juntos\".", desmotivacion: "Apontar seus erros na frente do grupo (a exposição social pode lhe gerar muita incomodidade)." },
      { situacion: "Facilitar uma mudança", activador: "Explicar como sua nova posição ajuda o time a estar melhor equilibrado.", desmotivacion: "Mudanças de time ou de grupo sem um processo de transição." }
    ],
    reseteo: `Quando {nombre} comete um erro, seu primeiro pensamento tende a ser: "Será que ficaram bravos comigo?". Acompanhamento sugerido: Usar a afirmação social. Provavelmente não precise de uma análise técnica profunda naquele instante, mas saber que o vínculo continua intacto. Um "Não tem problema, continuamos contando com você!" tende a ser o melhor botão de reinício para seu sistema.`,
    ecos: `Em casa: Tende a valorizar muito os rituais familiares (jantar juntos, um abraço antes de dormir). Seu bem-estar provavelmente dependa da qualidade da conexão com seus referentes afetivos. Na escola: Costuma mediar nos conflitos do recreio. Tende a aprender muito bem por meio da tutoria entre pares (acompanhando outros ou recebendo acompanhamento de um amigo).`,
    checklist: {
      antes: `O objetivo pode girar em torno da participação. "Hoje vamos aproveitar para jogar com seus amigos".`,
      durante: `Evitar as sinalizações negativas. Se precisar ajustar algo, fazê-lo com um tom de voz suave e em particular.`,
      despues: `Valorizar o aspecto humano. Perguntar: "Como você se sentiu hoje com o time?", "A quem você sentiu que acompanhou mais?".`,
    },
  },

  conector_reflexivo: {
    label: `Conector Reflexivo`,
    perfil: `Coesão Profunda e Observação do Clima do Grupo`,
    perfilExtended: `Percebe o estado emocional do time com uma sensibilidade pouco frequente. Tende a ser a cola silenciosa que faz todos se sentirem parte de algo maior, sem precisar ser o centro das atenções. Sua força está na sabedoria social: detecta quando alguém precisa de apoio antes que o resto perceba.`,
    bienvenida: `Este mapa é um convite para entender como {nombre} percebe e sente o esporte neste momento. Na Nave Argo, a força não está apenas no remo, mas na capacidade de ler o vento e o mar. Este relatório é uma "fotografia do presente" criada para que os adultos possamos sintonizar com seu ritmo natural, protegendo seu bem-estar e garantindo que o esporte continue sendo seu lugar seguro. Nota de segurança: Não realizamos diagnósticos nem avaliamos o rendimento. Nosso objetivo é identificar o contexto onde {nombre} flui com menor fricção emocional para favorecer sua continuidade esportiva.`,
    wow: `Na tripulação da Nave Argo, {nombre} tende a ocupar o lugar de quem detecta as correntes invisíveis. É provável que seja o tripulante que não precisa gritar para ser ouvido, porque seu valor reside em sua capacidade de entender o que o time precisa antes que os demais percebam. É provável que você perceba que {nombre} tende a observar muito antes de participar plenamente. Sua contribuição à tripulação costuma ser a coesão desde a calma. Não parece buscar ser o centro das atenções, mas o "cola silencioso" que faz todos se sentirem parte de algo maior. Sua grande força tende a ser a sabedoria social: a capacidade de perceber quem está triste, quem está sozinho ou quando o time perdeu a sintonia, trazendo uma presença equilibrada que suaviza as tensões.`,
    motorDesc: `O perfil de {nombre} se associa a um ritmo naturalmente profundo. Num contexto esportivo que costuma exigir velocidade imediata, é importante entender que seu ritmo não sugere falta de energia, mas riqueza de processamento. Um olhar mais próximo: Entrar no jogo pode ser como entrar em uma conversa profunda: provavelmente precise escutar primeiro para saber o que dizer depois. Sua maneira de estar parece escanear o clima emocional e as posições antes de ativar seus músculos. Se parecer pausado no início, é provável que esteja integrando todas as informações do entorno. Convite de sintonia: Dar-lhe tempo de "aterrissagem". Não lançá-lo à ação sem aviso prévio. Permitir-lhe observar os primeiros minutos do treino pode ajudar seu ritmo a se sincronizar com o do grupo.`,
    combustible: `O combustível de {nombre} tende a ser a aceitação e o pertencimento genuíno. É provável que não o motive ganhar por ganhar, mas a sensação de que faz parte de um grupo onde é apreciado por quem é. Feedback de sintonia: Tende a valorizar muito o feedback privado e afetuoso. Um "vi como você se alegrou com o passe do seu companheiro, gosto que você esteja atento a eles" pode ter muito mais impacto do que um aplauso público que coloque {nombre} no centro de todas as atenções.`,
    grupoEspacio: `No time: Tende a se vincular por meio da empatia e do tempo compartilhado. Costuma preferir as conversas um a um ou os grupos pequenos onde o ruído emocional é baixo. As injustiças ou os gritos o afetam profundamente, mesmo que não sejam dirigidos a ele, porque seu sistema tende a ser um receptor do clima grupal. No espaço: Costuma se sentir à vontade em zonas onde pode ter uma visão global. Muitas vezes pode preferir posições que lhe permitam ver todo o campo, pois isso parece lhe dar a segurança de entender a "história" do que está acontecendo no jogo.`,
    corazon: `É valioso traduzir sua pausa para não julgá-la como desinteresse: O que pode parecer: Às vezes pode dar a impressão de estar distraído, tímido ou que "lhe falta intensidade". O que provavelmente é (A Intenção): Uma busca de segurança emocional. {nombre} tende a não querer cometer um erro que quebre a harmonia do time. Sua pausa costuma ser um ato de respeito pelo jogo e pelos demais. O termômetro emocional: Sua frustração pode se manifestar como um "recuo". Se o ambiente ficar hostil ou muito competitivo, tende a se fechar em si mesmo e parar de participar ativamente para proteger seu equilíbrio interno.`,
    palabrasPuente: ["Observa", "Sente", "Juntos", "No seu ritmo", "Tranquilo", "Pertencimento"],
    palabrasRuido: ["Reaja sem pensar!", "Por que não participa?", "Todos já fizeram", "Seja mais intenso", "Não fique só olhando"],
    guia: [
      { situacion: "Manter sua conexão", activador: "Convidá-lo a um papel de observação ou de acompanhamento a um companheiro novo.", desmotivacion: "Colocá-lo no centro de uma competição individual e eliminatória." },
      { situacion: "Acompanhar sua confiança", activador: "Uma mensagem em voz baixa: \"Toma seu tempo, estou aqui com você\".", desmotivacion: "Expor seus silêncios ou seu ritmo pausado como algo que precisa ser mudado." },
      { situacion: "Facilitar uma mudança", activador: "Introduzir as mudanças de forma gradual, explicando o lado humano (ex: \"seu amigo precisa de você nessa zona\").", desmotivacion: "Mudanças bruscas de time que o separem de seus referentes afetivos de repente." }
    ],
    reseteo: `Quando {nombre} comete um erro, seu sistema tende a "congelar" emocionalmente. Pode se sentir desconectado do grupo pelo ocorrido. Acompanhamento sugerido: Oferecer-lhe uma saída que use sua força: a observação. Dizer-lhe: "Não se preocupe com essa jogada, agora fique atento a como eles se movem para que na próxima você saiba onde estar". Isso lhe dá uma tarefa de processamento que pode tirá-lo da emoção e devolvê-lo ao jogo desde sua zona de conforto: a análise do clima.`,
    ecos: `Em casa: Tende a precisar de "tempo de descompressão" ao chegar da escola. É provável que seja melhor não perguntar "como foi?" assim que chega; deixar que seu ritmo baixe e ele virá por conta própria contar as coisas quando se sentir em sintonia. Na escola: Costuma ser um excelente companheiro, alguém que ouve e que prefere os ambientes de aprendizagem tranquilos. Pode precisar de mais tempo para entregar tarefas criativas porque tende a colocar muita carga emocional e detalhe nelas.`,
    checklist: {
      antes: `Chegar com tempo extra para que possa ver o ambiente. O caos de chegar tarde tende a desajustar seu ritmo de Conector Reflexivo para toda a partida.`,
      durante: `Evitar as indicações em voz alta. Sua presença silenciosa e um gesto de aprovação ocasional costumam ser suficientes.`,
      despues: `Valorizar o bem-estar. Perguntar: "Como você se sentiu hoje com seus amigos?", "Houve algum momento que te fez sorrir?".`,
    },
  },

  sosten_agil: {
    label: `Sustento Ágil`,
    perfil: `Auxílio Veloz e Apoio Dinâmico`,
    perfilExtended: `Tem um radar especial para detectar quando um companheiro precisa de ajuda ou quando fica um espaço vazio em campo. Combina a disposição natural de acompanhar com um ritmo de resposta ágil, agindo antes de ser solicitado. Sua presença traz segurança reativa sem frear o movimento do time.`,
    bienvenida: `Este mapa nos convida a entender como {nombre} escolhe habitar o esporte hoje. Na Nave Argo, a segurança da travessia depende de quem garante que cada peça esteja em seu lugar. Este relatório não é uma etiqueta fixa, mas uma "fotografia do presente" criada para que os adultos possamos sintonizar com sua natureza, protegendo sua autoestima e sua vontade de continuar jogando. Nota de segurança: Não avaliamos talento nem realizamos diagnósticos. Nosso objetivo é identificar o contexto onde {nombre} flui com maior conforto e menor estresse.`,
    wow: `No mito dos Argonautas, {nombre} tende a ser aquele tripulante atento que, enquanto todos olham para o horizonte, detecta uma pequena fissura no casco e a repara no instante. Sua natureza parece ser a da proteção ativa. É provável que você perceba que {nombre} tem um "radar" especial para detectar quando um companheiro precisa de ajuda ou quando ficou um espaço vazio em campo. Sua contribuição à tripulação costuma ser a segurança reativa: não parece buscar o protagonismo do gol, mas a satisfação de saber que "o time está seguro" graças à sua intervenção. Sua grande força tende a ser a onipresença de apoio: estar onde é necessário, exatamente no momento em que é necessário.`,
    motorDesc: `O perfil de {nombre} se associa a um ritmo naturalmente ágil. Mas diferente de outros perfis ágeis que usam essa velocidade para atacar, {nombre} tende a usá-la para assistir. Um olhar mais próximo: Seu sistema nervoso parece estar em "alerta amável". Sua velocidade de reação tende a se ativar ante a necessidade do outro. Se uma bola fica solta ou um companheiro perde sua posição, seu corpo parece responder de forma quase instintiva. Não precisa pensar muito a jogada; sua inteligência tende a ser de auxílio imediato. Convite de sintonia: Valorizar sua capacidade de estar atento. Um "que bem você cobriu esse espaço" pode confirmar-lhe que seu ritmo ágil está cumprindo sua missão de proteger o grupo.`,
    combustible: `O combustível de {nombre} tende a ser sentir-se útil e necessário. É provável que se sinta vibrante quando percebe que seu esforço silencioso evitou uma dificuldade para o time. Sua motivação parece ser relacional: "jogo para que meu time esteja bem". Feedback de sintonia: Tende a se nutrir da validação do esforço invisível. Em vez de pedir-lhe que "brilhe sozinho", tentar: "Hoje você foi o motor que manteve todos seguros, sem você o time não teria estado tão organizado". Isso reforça sua identidade de sustento.`,
    grupoEspacio: `No time: Tende a ser o companheiro que sempre tem um gesto de ajuda. É provável que seja quem recolhe os materiais sem ser pedido ou quem ajuda um companheiro a amarrar o tênis. Vincula-se pelo serviço. No espaço: Costuma se sentir à vontade em posições de cobertura. Gosta de ter o jogo de frente para poder identificar onde faz falta sua ajuda. Os espaços vazios não o assustam; tende a vê-los como "missões de auxílio" que deve cumprir.`,
    corazon: `Para sintonizar com {nombre}, é valioso traduzir sua tendência de ficar em segundo plano: O que pode parecer: Às vezes pode dar a impressão de que "não quer ser o protagonista" ou que lhe falta ambição individual. O que provavelmente é (A Intenção): Um alto senso de responsabilidade coletiva. {nombre} tende a sentir que se deixar seu posto de apoio para buscar o brilho pessoal, o time ficará vulnerável. Sua aparente "falta de ambição" costuma ser na verdade uma entrega total ao bem-estar do grupo. O termômetro emocional: Sua frustração pode aparecer quando sente que sua ajuda não é valorizada ou quando o ambiente está tão desordenado que não sabe a quem acompanhar primeiro. Aí pode se sentir sobrecarregado e perder sua eficácia.`,
    palabrasPuente: ["Apoio", "Garante", "Acompanha", "Soma", "Equilíbrio", "Precisamos de você aí"],
    palabrasRuido: ["Esqueça os outros", "Faz o seu", "Não se preocupe com o grupo", "Destaque-se sozinho", "Não assista ninguém"],
    guia: [
      { situacion: "Manter sua conexão", activador: "Oferecer uma \"missão de apoio\" específica (ex: \"Seu papel é acompanhar a defesa para que esteja tranquila\").", desmotivacion: "Deixá-lo em uma posição onde não tenha ninguém para acompanhar ou assistir." },
      { situacion: "Acompanhar sua confiança", activador: "Validar seu trabalho silencioso e invisível: \"Vi aquela cobertura que você fez, foi fundamental\".", desmotivacion: "Exigir que assuma riscos individuais excessivos que deixem o time exposto." },
      { situacion: "Facilitar uma mudança", activador: "Explicar como sua nova função é vital para a segurança da Nave.", desmotivacion: "Fazer mudanças que pareçam uma falta de confiança em sua capacidade de acompanhamento." }
    ],
    reseteo: `Quando {nombre} comete um erro, tende a sentir que "falhou com o time". Acompanhamento sugerido: Não pedir que esqueça. Dar-lhe uma nova tarefa de acompanhamento. Dizer-lhe: "Essa não saiu, mas agora seu companheiro precisa que você cubra essa zona, vai acompanhá-lo!". Ao colocar seu ritmo ágil a serviço de outro, seu sistema nervoso tende a "limpar" o erro próprio e recuperar a sintonia de imediato.`,
    ecos: `Em casa: Tende a reagir rapidamente quando vê que você precisa de ajuda com as sacolas de compra ou pondo a mesa. É provável que valorize muito que você lhe dê "missões de ajuda" em casa; isso o faz se sentir parte importante da família. Na escola: Costuma ser o companheiro que empresta os lápis ou ajuda a explicar algo para quem não entendeu. Tende a se sentir seguro em papéis de acompanhamento ou assistência.`,
    checklist: {
      antes: `O objetivo pode girar em torno da assistência (ex: "Hoje vamos nos concentrar em como você está atento para acompanhar seus companheiros").`,
      durante: `Evitar pedir-lhe que "parta para o ataque" se isso implicar abandonar seu papel de sustento. Valorizar seu posicionamento.`,
      despues: `A conversa pode se centrar em seu valor para o time: "A quem você sentiu que acompanhou mais hoje?", "Em que momento sentiu que o time estava seguro graças a você?".`,
    },
  },

  sosten_confiable: {
    label: `Sustento Confiável`,
    perfil: `Consistência Serena e Apoio Estruturado`,
    perfilExtended: `Sua maior força é a previsibilidade positiva: o time pode contar que sempre estará onde precisa estar. Tende a manter a calma e a ordem quando outros começam a perder os nervos, sendo a base estável do grupo. Não busca os holofotes, mas sua ausência seria sentida imediatamente.`,
    bienvenida: `Este mapa é um convite para compreender como {nombre} escolhe habitar o esporte hoje. Na Nave Argo, a segurança da viagem não depende apenas da velocidade, mas da solidez de quem mantém o rumo sem fraquejar. Este relatório é uma "fotografia do presente" criada para que os adultos possamos sintonizar com seu ritmo, protegendo seu bem-estar e garantindo que o esporte seja seu lugar de confiança. Nota de segurança: Não avaliamos talento nem realizamos diagnósticos de saúde mental. Nosso objetivo é identificar o contexto onde {nombre} flui com maior conforto para evitar o estresse desnecessário.`,
    wow: `No mito dos Argonautas, {nombre} tende a ser aquele tripulante que garante que cada cabo esteja bem amarrado e que o ritmo do remo seja constante, não importa se o mar está calmo ou agitado. Sua natureza parece ser a da presença incondicional. É provável que você perceba que {nombre} não busca os holofotes nem faz as jogadas mais vistosas, mas tende a ser quem nunca abandona sua posição. Sua contribuição à tripulação costuma ser a confiabilidade absoluta: tende a ser o "seguro de vida" do time. Seu valor não reside na surpresa, mas na repetição do que funciona. Sua grande força tende a ser a estabilidade emocional: a capacidade de manter a calma e a ordem quando os demais começam a perder os nervos.`,
    motorDesc: `O perfil de {nombre} se associa a um ritmo naturalmente equilibrado. Isso se traduz em um processamento harmônico: não tende a ser impulsivo nem excessivamente pausado; é rítmico. Um olhar mais próximo: Seu sistema nervoso parece preferir a previsibilidade. Tende a precisar entender a sequência do que vai acontecer para colocar seu ritmo em marcha. Se o treino segue uma estrutura clara, {nombre} provavelmente renderá ao máximo. As mudanças bruscas de planos ou os exercícios desordenados podem desajustar sua sincronia, não por falta de capacidade, mas porque sua maneira de processar parece estar projetada para a eficiência técnica e a ordem. Convite de sintonia: Antecipá-lo sobre o que vai acontecer. "Primeiro faremos isso e depois aquilo". Essa pequena estrutura pode dar-lhe a segurança necessária para que seu ritmo equilibrado funcione como um relógio.`,
    combustible: `O combustível de {nombre} tende a ser a competência e o dever cumprido. É provável que se sinta motivado quando sabe exatamente o que se espera e consegue realizá-lo de forma correta. Não parece buscar o aplauso massivo, mas a satisfação interna de "ter feito sua parte". Feedback de sintonia: Tende a valorizar muito o reconhecimento de sua consistência. Em vez de pedir-lhe que faça algo "incrível", tentar: "Me dá muita segurança ver você em campo porque você sempre está onde precisa estar". Isso valida sua identidade de sustento confiável.`,
    grupoEspacio: `No time: Tende a se vincular por meio da lealdade e do respeito aos acordos. É provável que seja o companheiro que respeita os turnos e que segue as instruções do treinador à risca. Costuma evitar os conflitos e ser uma figura conciliadora que traz "normalidade" ao grupo. No espaço: Tende a se sentir à vontade em zonas bem definidas. Gosta de ter uma "parcela" de responsabilidade clara em campo. Se sabe que "essa é sua zona", provavelmente a defende com uma tenacidade admirável. A desordem espacial (todos correndo atrás da bola) pode lhe gerar uma fadiga mental maior do que a outros perfis.`,
    corazon: `Para sintonizar com {nombre}, é valioso valorizar sua moderação: O que pode parecer: Às vezes pode dar a impressão de que "não arrisca" ou que é muito conservador em seu jogo. O que provavelmente é (A Intenção): Um desejo profundo de preservar a segurança do time. {nombre} tende a sentir que arriscar desnecessariamente é colocar em perigo o equilíbrio do grupo. Sua "cautela" costuma ser na verdade uma gestão responsável do jogo. O termômetro emocional: Sua frustração tende a ser silenciosa. Se o ambiente ficar muito errático ou se os acordos não forem cumpridos, pode começar a se mostrar apático ou desmotivado, provavelmente porque o entorno deixou de ser "lógico" para seu sistema.`,
    palabrasPuente: ["Constante", "Seguro", "Ordem", "Cumprir", "Passo a passo", "Confiança"],
    palabrasRuido: ["Inventa algo!", "Muda tudo agora", "Faz o que quiser", "Esqueça o plano", "Não siga a estrutura"],
    guia: [
      { situacion: "Manter sua conexão", activador: "Oferecer uma função clara e estável (ex: \"Sua tarefa hoje é cuidar dessa posição\").", desmotivacion: "Mudá-lo de posição ou de tarefa a cada cinco minutos sem explicação." },
      { situacion: "Acompanhar sua confiança", activador: "Validar sua confiabilidade: \"Você fez exatamente o que o time precisava\".", desmotivacion: "Pressioná-lo para que seja \"criativo\" ou \"explosivo\" de forma forçada." },
      { situacion: "Facilitar uma mudança", activador: "Explicar a mudança com lógica e antecedência: \"A partir de agora, vamos tentar isso para...\".", desmotivacion: "Modificações abruptas de última hora no time ou nos acordos." }
    ],
    reseteo: `Quando {nombre} comete um erro, tende a se sentir desajustado porque "saiu do plano". Acompanhamento sugerido: Devolver-lhe a estrutura. Não buscar uma reação emocional, buscar uma técnica. Dizer-lhe: "Não tem problema, volta à sua posição e lembra o passo 1 e o passo 2". Ao lembrar-lhe o procedimento, sua mente tende a voltar a sentir que tem o rumo e seu ritmo equilibrado recupera a sintonia.`,
    ecos: `Em casa: Tende a agradecer as rotinas. Saber o que vai jantar ou o que faremos no fim de semana provavelmente lhe dá muita paz mental. É provável que seja alguém em quem "você pode confiar" para cumprir com suas pequenas responsabilidades diárias sem precisar lembrá-lo constantemente. Na escola: Costuma ter um perfil acadêmico metódico. Se sai muito bem em matérias que têm processos claros e lógica. Pode preferir as provas onde sabe exatamente quais temas serão avaliados antes das de "criatividade aberta".`,
    checklist: {
      antes: `Manter a rotina pré-jogo (mesmo horário, mesma mochila). A previsibilidade tende a ser seu melhor aquecimento mental.`,
      durante: `Evitar as indicações emocionais. Se precisar ajustar algo, ofereça-o como um dado técnico concreto.`,
      despues: `Valorizar a consistência. Perguntar: "Em que momento você sentiu que estava com tudo em ordem?", "Você se sentiu confortável seguindo o plano do time?".`,
    },
  },

  sosten_sereno: {
    label: `Sustento Sereno`,
    perfil: `Imperturbabilidade e Calma Estrutural`,
    perfilExtended: `Tende a manter a calma quando a pressão aumenta, transmitindo uma estabilidade que organiza quem o rodeia. Seu ritmo profundo não é lentidão: é sua maneira de ser a âncora emocional do time quando a partida fica desordenada. Sua melhor versão costuma aparecer quando o cansaço começa a afetar os demais.`,
    bienvenida: `Este mapa é um convite para compreender como {nombre} escolhe habitar o esporte hoje. Na Nave Argo, a segurança da missão depende de quem mantém a calma quando o restante da tripulação entra em alerta. Este relatório é uma "fotografia do presente" criada para que os adultos possamos sintonizar com seu ritmo, protegendo seu bem-estar e garantindo que o esporte seja seu refúgio de confiança. Nota de segurança: Não avaliamos talento nem realizamos diagnósticos de saúde mental. Nosso objetivo é identificar o contexto onde {nombre} flui com maior conforto para evitar o estresse desnecessário e estimular seu prazer.`,
    wow: `No mito dos Argonautas, {nombre} tende a ser aquele tripulante que, no meio da neblina mais densa, permanece sentado em seu lugar, mantendo o ritmo do remo com uma paz que tranquiliza todos os demais. Sua natureza parece ser a da estabilidade profunda. É provável que você perceba que {nombre} parece "não sentir a pressão". Enquanto outros se aceleram ou se frustram, {nombre} tende a manter sua expressão e seu ritmo. Sua contribuição à tripulação costuma ser a calma estrutural: tende a ser a âncora emocional do time. Seu valor não reside na velocidade de seu ataque, mas em sua capacidade de nunca se desorganizar. Sua grande força tende a ser a imperturbabilidade: ser o lugar seguro para onde seus companheiros podem olhar quando a partida fica desordenada.`,
    motorDesc: `O perfil de {nombre} se associa a um ritmo naturalmente profundo. É fundamental que como adultos entendamos que esse ritmo é seu maior recurso: seu sistema nervioso parece processar a informação a uma profundidade que requer tempo, mas que uma vez ativada, tende a ser imparável. Um olhar mais próximo: Seu ritmo parece funcionar por inércia. Pode ser que tenha dificuldade no arranque inicial e nas mudanças bruscas, mas uma vez que encontra sua "velocidade de cruzeiro", tende a mantê-la durante horas sem se fatigar mentalmente. Se parece que não reage a uma consigna urgente, é provável que não seja desobediência; é que seu ritmo parece projetado para a resistência, não para a explosividade. Convite de sintonia: Não tentar acelerar seu processo de "arranque". Dar-lhe os primeiros minutos da partida para que seu sistema se asente. É provável que sua melhor versão apareça quando o cansaço começa a afetar os demais, mas {nombre} continua como se nada.`,
    combustible: `O combustível de {nombre} tende a ser a paz e o senso de pertencimento. É provável que se sinta vibrante quando o ambiente é previsível, amável e estável. Motiva-o saber que sua presença ajuda o time a estar tranquilo. Feedback de sintonia: Tende a valorizar muito o reconhecimento de seu equilíbrio. Em vez de pedir-lhe que seja "mais intenso", tentar: "Adoro a tranquilidade que você transmite ao time, você nos ajuda a todos a pensar melhor". Isso valida sua identidade de sustento sereno.`,
    grupoEspacio: `No time: Tende a se vincular por meio da lealdade silenciosa. É provável que seja o companheiro que não busca conflitos e que está sempre disponível para um amigo. Sua forma de cuidar do grupo costuma ser estar presente. É provável que seja quem todos querem ter por perto quando as coisas vão mal, porque sua calma tende a ser contagiante. No espaço: Costuma se sentir à vontade em posições de retaguarda ou de apoio. Gosta de ter o panorama completo à sua frente. A aglomeração de jogadores pode lhe resultar estressante; tende a preferir as zonas onde pode manter sua estrutura e sua ordem técnica sem interferências.`,
    corazon: `Para sintonizar com {nombre}, é valioso entender o que há por trás de seu ritmo pausado: O que pode parecer: Às vezes pode dar a impressão de ser passivo, de que "lhe faltam vontade" ou que não está conectado com a intensidade da partida. O que provavelmente é (A Intenção): Uma busca de preservação do equilíbrio. {nombre} tende a sentir que a super-excitação não lhe serve. Sua pausa costuma ser uma forma de garantir que cada movimento que faça seja sólido e seguro. Sua aparente "falta de intensidade" provavelmente seja na verdade uma economia de esforço estratégica. O termômetro emocional: Sua frustração tende a ser quase invisível. Se se sentir excessivamente pressionado para agir rápido, pode simplesmente "desconectar-se". Deixará de participar não por raiva, mas por saturação sensorial.`,
    palabrasPuente: ["Tranquilo", "No seu ritmo", "Firme", "Sólido", "Confio na sua calma", "Passo a passo"],
    palabrasRuido: ["Explode!", "Reaja já!", "Mais intensidade!", "Não pense tanto", "Todos já começaram"],
    guia: [
      { situacion: "Manter sua conexão", activador: "Oferecer um papel de \"organizador da calma\" ou de último recurso de segurança.", desmotivacion: "Submetê-lo a uma pressão constante de velocidade ou resultados imediatos." },
      { situacion: "Acompanhar sua confiança", activador: "Validar sua imperturbabilidade: \"Que bem você manteve seu lugar apesar do caos\".", desmotivacion: "Gritar para que \"reaja\" a uma jogada que não saiu." },
      { situacion: "Facilitar uma mudança", activador: "Explicar a mudança com muita antecedência e suavidade, apelando para a segurança do time.", desmotivacion: "Mudanças de posição \"surpresa\" ou de última hora que quebrem sua inércia de jogo." }
    ],
    reseteo: `Quando {nombre} comete um erro, seu sistema não tende a entrar em alerta, mas pode "desacelerar" ainda mais. Acompanhamento sugerido: Não buscar uma reação rápida. Oferecer um gesto de calma. Um simples "Seguimos igual, confio em você" pode ser suficiente. Sua mente tende a precisar sentir que o erro não destruiu a estabilidade do entorno para voltar a colocar seu ritmo em marcha.`,
    ecos: `Em casa: Tende a trazer paz para casa. Costuma não gerar conflitos, mas provavelmente precise de seus tempos de silêncio. É provável que valorize muito que não o apresse pela manhã para ir à escola; tende a precisar de um despertar suave para que seu ritmo comece a se ativar em sintonia. Na escola: Costuma não travar nas provas difíceis. Pode demorar mais para terminar, mas seu nível de precisão tende a ser alto devido ao seu processamento profundo.`,
    checklist: {
      antes: `Garantir um ambiente tranquilo. Evitar as pressas e os estímulos excessivamente barulhentos antes de sair de casa.`,
      durante: `Observar sua linguagem corporal. Se notar quietude excessiva, não pedir velocidade; convidar com um "objetivo de posição" pequeno.`,
      despues: `Valorizar sua resistência. Perguntar: "Como você conseguiu manter a calma quando todos corriam?", "Você se sentiu confortável ajudando o time a estar tranquilo?".`,
    },
  },

  estratega_reactivo: {
    label: `Estrategista Reativo`,
    perfil: `Precisão Instantânea e Ajuste Tático Veloz`,
    perfilExtended: `Lê o jogo com rapidez e age sobre o que analisa sem demora. Tende a detectar quando um companheiro está mal posicionado ou quando um acordo não está sendo cumprido, antes que os demais notem. Sua combinação de análise e imediatez o torna o olho do treinador dentro do campo.`,
    bienvenida: `Este mapa é um convite para entender como {nombre} processa o esporte hoje. Na Nave Argo, a vitória depende de quem sabe ler as estrelas e ajustar as velas a tempo. Este relatório é uma "fotografia do presente" criada para que os adultos acompanhemos sua natureza analítica, protegendo sua autoestima e garantindo que sua busca pela precisão seja uma fonte de prazer. Nota de segurança: Isso não é um diagnóstico clínico. É uma ferramenta para identificar o contexto onde {nombre} flui com menor fricção emocional.`,
    wow: `No mito dos Argonautas, {nombre} tende a ser Tifis, o timoneiro capaz de detectar uma rocha submersa muito antes que os demais. Sua natureza parece ser a da vigilância técnica. É provável que você perceba que {nombre} tende a ser o primeiro a perceber se um companheiro está mal posicionado ou se um acordo não está sendo cumprido. Sua contribuição à tripulação costuma ser a antecipação preventiva: não parece buscar a bola por impulso, mas para colocar ordem. Sua grande força tende a ser a agudeza perceptiva: a capacidade de processar a tática a uma velocidade surpreendente, tornando-se o "olho do treinador" dentro do campo.`,
    motorDesc: `O perfil de {nombre} se associa a um ritmo naturalmente ágil. Em seu caso, a agilidade não parece ser física (correr mais), mas mental. Um olhar mais próximo: Sua mente parece funcionar como um scanner que processa em alta velocidade. Tende a detectar padrões, oportunidades e detalhes de forma quase imediata. Se você notar que ele sinaliza ou dá indicações rápidas a seus companheiros, é provável que não queira dirigir, mas que seu ritmo processe o "dever ser" do jogo tão rápido que sente a necessidade de comunicá-lo para que o time funcione melhor. Convite de sintonia: Valorizar sua leitura. Um "que boa visão você teve aí" pode confirmar-lhe que seu ritmo de estrategista está cumprindo sua missão de dar clareza ao grupo.`,
    combustible: `O combustível de {nombre} tende a ser a precisão e a ordem. É provável que se sinta vibrante quando o plano sai "limpo" e quando sente que seu conhecimento dos acordos ajuda o time. Motiva-o a sensação de "fazer as coisas bem feitas". Feedback de sintonia: Tende a se nutrir do feedback lógico. Em vez de um "Muito bem!", tentar: "Essa antecipação de posição que você fez foi exata para recuperar a bola". Isso valida seu processo de pensamento e o faz se sentir competente.`,
    grupoEspacio: `No time: Tende a se vincular por meio da clareza e da norma. É provável que seja o companheiro que lembra os acordos e que espera que todos cumpram com sua parte. Sua lealdade costuma se demonstrar garantindo que o time não cometa tropeços evitáveis. No espaço: Tende a se sentir à vontade em posições de visão periférica. Gosta de estar onde possa "ver o tabuleiro" completo. A falta de consignas claras ou de uma lógica visível pode gerar-lhe um estresse imediato; tende a precisar que o espaço tenha um sentido.`,
    corazon: `Para sintonizar com {nombre}, é valioso traduzir sua "exigência": O que pode parecer: Às vezes pode dar a impressão de "saber tudo" ou de apontar demais seus companheiros. O que provavelmente é (A Intenção): Um desejo de excelência coletiva. {nombre} não aponta por maldade; tende a sofrer se o time perde a ordem porque sente que assim ficam mais vulneráveis. Sua intenção costuma ser proteger o sucesso do grupo por meio da ordem. O termômetro emocional: Sua frustração tende a ser reativa e técnica. Se o árbitro erra ou um companheiro ignora uma indicação óbvia, seu ritmo ágil pode saltar em forma de protesto ou de um gesto de "braços caídos".`,
    palabrasPuente: ["Precisão", "Lógica", "Analisa", "Ajuste", "Tática", "Presta atenção em..."],
    palabrasRuido: ["Não importa como sair", "As regras não importam", "Chuta sem pensar", "Esqueça o plano", "Não analise tanto"],
    guia: [
      { situacion: "Manter sua conexão", activador: "Oferecer uma \"missão de ajuste\" (ex: \"Ajuda-nos a que a defesa mantenha a linha\").", desmotivacion: "Consignas ambíguas ou treinos baseados apenas no acaso." },
      { situacion: "Acompanhar sua confiança", activador: "Validar sua lógica: \"Você tem razão no que viu, agora vamos ver como comunicá-lo melhor\".", desmotivacion: "Minimizar sua atenção aos acordos e à ordem." },
      { situacion: "Facilitar uma mudança", activador: "Explicar a lógica técnica por trás da mudança de posição ou de grupo.", desmotivacion: "Mudanças de planos sem uma explicação coerente que possa ser processada." }
    ],
    reseteo: `Quando {nombre} comete um erro, seu ritmo ágil pode entrar em "loop de análise": tende a ficar pensando no que falhou tecnicamente. Acompanhamento sugerido: Oferecer-lhe um novo dado tático. Não dizer "já passou". Dizer: "Você analisou bem, mas o vento mudou a trajetória. Na próxima, ajuste um metro para a esquerda". Ao dar-lhe uma solução técnica, sua mente tende a "fechar" o erro e voltar ao presente com uma missão clara.`,
    ecos: `Em casa: Tende a te lembrar se você pulou um passo de uma receita ou se está na hora de sair. É provável que valorize muito que você seja coerente com os acordos que estabelece. Na escola: Costuma se destacar em matemática ou ciências, onde há uma "resposta correta" e uma lógica a seguir. Pode se frustrar se o professor é desorganizado.`,
    checklist: {
      antes: `Revisar o "objetivo tático" do dia. Saber o que precisa observar lhe dá muita segurança.`,
      durante: `Evitar as indicações emocionais. Usar sinais breves que apelem para sua visão do campo (ex: "Escaneia o espaço!").`,
      despues: `A conversa pode girar em torno do "ajuste técnico". Perguntar: "O que foi o mais interessante que você notou hoje na defesa do outro time?".`,
    },
  },

  estratega_analitico: {
    label: `Estrategista Analítico`,
    perfil: `Processamento Técnico e Execução com Propósito`,
    perfilExtended: `Processa a informação antes de ativar a resposta, o que lhe dá uma precisão na execução que se destaca dentro do time. Tende a precisar entender o sentido do que faz, e uma vez que entende, aplica o plano com uma fidelidade que traz ordem coletiva. Sua força está na qualidade de suas decisões, não na velocidade.`,
    bienvenida: `Este mapa é um convite para compreender como {nombre} processa e habita o esporte hoje. Na Nave Argo, o sucesso da missão não depende apenas da força, mas da exatidão dos cálculos. Este relatório é uma "fotografia do presente" criada para que os adultos possamos sintonizar com seu ritmo analítico, protegendo sua autoestima e garantindo que o esporte seja um espaço de aprendizado e prazer. Nota de segurança: Não avaliamos talento nem realizamos diagnósticos. Nosso objetivo é identificar o contexto onde {nombre} flui com maior conforto e menor estresse.`,
    wow: `No mito dos Argonautas, {nombre} tende a ser aquele tripulante que estuda as estrelas e os mapas antes de a nave zarpar. Sua natureza parece ser a da preparação inteligente. É provável que você perceba que {nombre} tende a valorizar profundamente as instruções. Sua contribuição à tripulação costuma ser a qualidade na execução: não parece buscar ser o mais rápido nem o mais barulhento, mas o mais preciso. Seu valor tende a residir em sua capacidade de seguir o plano de jogo com uma fidelidade que traz ordem a todo o time. Sua grande força tende a ser a atenção ao detalhe: a capacidade de notar esses pequenos ajustes técnicos que fazem uma jogada passar de "boa" a "perfeita".`,
    motorDesc: `O perfil de {nombre} se associa a um ritmo naturalmente equilibrado. Isso sugere que seu sistema prefere processar a informação antes de ativar a resposta física. Um olhar mais próximo: O esporte provavelmente seja um desafio que precisa ser resolvido corretamente. Não "chuta a bola" por chutar; sua mente tende a avaliar a posição, a força e a direção. Se às vezes parece que se toma um instante a mais, é provável que não seja dúvida, mas calibração. Uma vez que seu ritmo equilibrado processa a instrução e a encontra lógica, sua execução costuma ser das mais limpas do grupo. Convite de sintonia: Dar-lhe tempo para "mastigar" a nova tática. É provável que depois de ver o exercício algumas vezes, o realize com uma precisão que surpreenda a todos.`,
    combustible: `O combustível de {nombre} tende a ser a competência técnica e a clareza. É provável que se sinta vibrante quando entende o "porquê" das coisas e quando consegue realizar um movimento exatamente como foi explicado. Motiva-o o domínio da técnica. Feedback de sintonia: Tende a se nutrir do feedback específico. Em vez de um "Muito bem!", tentar: "Percebi como você posicionou o pé para aquele passe, foi tecnicamente perfeito". Isso valida seu processo mental e seu esforço pela precisão.`,
    grupoEspacio: `No time: Tende a se vincular por meio da tarefa compartilhada. Costuma respeitar muito os companheiros que se esforçam para jogar bem e que seguem os acordos. Não costuma buscar a liderança emocional, mas tende a ser uma referência tática para os demais: "se quiser saber como se faz esse exercício, olha para {nombre}". No espaço: Costuma se sentir à vontade em entornos estruturados. Gosta de saber quais são os limites do campo e qual é sua posição exata. A desordem ou os treinos onde "tudo vale" podem gerar-lhe uma fadiga mental invisível porque sua mente tende a tentar encontrar uma ordem onde não há.`,
    corazon: `Para sintonizar com {nombre}, é valioso entender o que há por trás de sua seriedade: O que pode parecer: Às vezes pode dar a impressão de certa meticulosidade, seriedade ou de escolher com cuidado antes de agir. O que provavelmente é (A Intenção): Um desejo de não falhar com o time. {nombre} tende a levar o jogo com responsabilidade porque sente que sua precisão é sua forma de ajudar. Sua "meticulosidade" costuma ser na verdade concentração e respeito pelo esporte. O termômetro emocional: Sua frustração tende a ser interna e técnica. Se não consegue realizar um movimento como sabe que deve ser feito, pode se mostrar mais silencioso do que o habitual, tomando um tempo interno para processar o ocorrido com detalhe. Tende a temer o desajuste técnico mais do que o resultado do placar.`,
    palabrasPuente: ["Técnica", "Precisão", "Plano", "Lógica", "Ajuste", "Como"],
    palabrasRuido: ["Como sair", "Não planeje", "Não pense", "Improvisa sem mais", "Esqueça a técnica"],
    guia: [
      { situacion: "Manter sua conexão", activador: "Propor-lhe desafios de precisão (ex: \"Hoje o objetivo é que 4 de cada 5 passes cheguem ao destino\").", desmotivacion: "Treinos desordenados ou baseados apenas no contato físico sem tática." },
      { situacion: "Acompanhar sua confiança", activador: "Validar a qualidade de seu processo: \"Vi como você pensou a jogada, a lógica era perfeita\".", desmotivacion: "Apontamentos genéricos ou comparações com companheiros que jogam de forma mais impulsiva." },
      { situacion: "Facilitar uma mudança", activador: "Explicar detalhadamente as novas regras e o sentido da mudança de posição.", desmotivacion: "Mudanças de planos de última hora que quebrem seu mapa mental do jogo." }
    ],
    reseteo: `Quando {nombre} comete um erro, seu sistema pode entrar em "modo análise técnica". Acompanhamento sugerido: Usar a lógica. Não pedir que esqueça. Dizer-lhe: "A análise estava boa, mas a execução se desviou pelo detalhe X. Na próxima, ajuste isso". Ao dar-lhe um dado técnico para ajustar, sua mente tende a "fechar" o erro e voltar ao presente com uma missão de melhora clara.`,
    ecos: `Em casa: Tende a preferir saber o "porquê" dos acordos. É provável que valorize muito que você seja coerente e que os planos sejam cumpridos. Gosta de ter seu espaço e seus materiais organizados à sua maneira. Na escola: Costuma ter um perfil acadêmico muito cumpridor, desfrutando das matérias com processos claros (matemática, gramática, música). Tende a precisar saber o que se espera exatamente em uma prova para não se sentir ansioso.`,
    checklist: {
      antes: `Garantir que saiba o horário e o lugar com antecedência. A previsibilidade tende a ser seu melhor aquecimento mental.`,
      durante: `Evitar as indicações constantes. Confiar em sua capacidade de auto-ajuste; ele provavelmente já sabe quando algo não saiu tecnicamente bem.`,
      despues: `A conversa pode girar em torno da inteligência do jogo. Perguntar: "O que você mais gostou de como funcionou hoje a tática do time?".`,
    },
  },

  estratega_observador: {
    label: `Estrategista Observador`,
    perfil: `Análise Profunda do Ambiente e Precisão Lógica`,
    perfilExtended: `Processa a informação com uma profundidade pouco comum, analisando posições, espaços e padrões antes de agir. Tende a observar a partida mesmo enquanto joga, com uma clareza estratégica que o torna a âncora inteligente do time. O que pode parecer lentidão costuma ser rigor: quando decide, o faz a partir de uma compreensão muito completa da situação.`,
    bienvenida: `Este mapa é um convite para descobrir como {nombre} processa o mundo do esporte hoje. Na Nave Argo, o sucesso não dependia apenas da força dos remadores, mas da capacidade do vigia para ler as correntes invisíveis. Este relatório é uma "fotografia do presente" criada para que os adultos sintonizem com seu ritmo analítico, protegendo sua autoestima e garantindo que sua inteligência seja sua maior fonte de prazer. Nota de segurança: Não avaliamos talento nem realizamos diagnósticos. Nosso objetivo é identificar o contexto onde {nombre} flui com menor fricção emocional para que nunca queira parar de jogar.`,
    wow: `No mito dos Argonautas, {nombre} tende a ser aquele que permanece em silêncio observando o horizonte, detectando padrões que os demais ignoram pela pressa. Sua natureza parece ser a da compreensão integral. É muito provável que você perceba que {nombre} tende a "observar a partida mesmo enquanto joga". Sua contribuição à tripulação costuma ser a clareza estratégica: não parece correr atrás da bola por instinto, mas busca entender para onde se dirige a jogada. Sua grande força tende a ser a visão periférica mental: a capacidade de processar a lógica do jogo desde uma calma imperturbável, tornando-se a âncora inteligente do time.`,
    motorDesc: `O perfil de {nombre} se associa a um ritmo naturalmente profundo. Num entorno esportivo que frequentemente exige imediatez, é vital entender que seu ritmo não sugere falta de capacidade, mas riqueza de dados processados. Um olhar mais próximo: Sua mente parece ser um processador de alta fidelidade. Antes de mover um músculo, tende a analisar a posição do adversário, o espaço disponível e a melhor opção técnica. Sua "pausa" inicial não parece ser dúvida, mas coleta de informações. Uma vez que tem a certeza do que deve fazer, sua execução costuma ser surpreendentemente precisa. Convite de sintonia: Permitir-lhe ser o observador. Se lhe forem dados alguns minutos para ver como outros fazem um exercício novo, seu ritmo tende a sintonizar muito melhor do que se for pedido que seja o primeiro a tentar.`,
    combustible: `O combustível de {nombre} tende a ser a compreensão. É provável que se sinta vibrante quando consegue decifrar como funciona o jogo do time adversário ou quando uma estratégia que previu se cumpre. Motiva-o a sensação de "ter a compreensão mental" da situação. Feedback de sintonia: Tende a valorizar o feedback intelectual. Em vez de elogios genéricos, tentar: "Percebi como você estava observando o defensor antes de dar aquele passe; sua leitura foi excelente". Isso valida sua identidade de estrategista.`,
    grupoEspacio: `No time: Tende a se vincular por meio do respeito técnico e da calma. Não costuma ser o que mais fala, mas é provável que seja a quem seus companheiros olham quando precisam de ordem. Sua lealdade tende a se demonstrar mantendo sua posição e cumprindo o plano com uma disciplina impecável. No espaço: Costuma se sentir à vontade em zonas que lhe permitam ver o campo completo. Tende a preferir ter espaço ao seu redor para poder pensar. O contato físico excessivo ou a aglomeração de jogadores pode lhe gerar uma fadiga mental imediata porque lhe impede de ler o jogo com clareza.`,
    corazon: `Para sintonizar com {nombre}, é valioso traduzir seu silêncio: O que pode parecer: Às vezes pode dar a impressão de estar distraído, tímido ou que "lhe falta intensidade" ante a dinâmica da partida. O que provavelmente é (A Intenção): Um desejo de agir com lógica. {nombre} tende a preferir não agir de forma desordenada ou por puro impulso. Sua pausa costuma ser um ato de respeito pela eficiência. Mover-se sem sentido provavelmente seja pior do que não se mover. O termômetro emocional: Sua frustração pode se apresentar como uma "pausa prolongada de análise". Se o jogo fica muito desordenado ou imprevisível, pode recuar e parar de participar porque sua mente não encontra um padrão a seguir.`,
    palabrasPuente: ["Analisa", "Presta atenção", "O que você vê", "Toma seu tempo", "Lógica", "Precisão"],
    palabrasRuido: ["Não pense!", "Reaja sem analisar!", "Corre como for!", "Esqueça o plano", "Não observe, age"],
    guia: [
      { situacion: "Manter sua conexão", activador: "Oferecer uma \"missão de leitura\": \"Presta atenção por onde eles estão atacando mais\".", desmotivacion: "Pedir-lhe que seja \"explosivo\" de forma constante e sem motivo tático." },
      { situacion: "Acompanhar sua confiança", activador: "Validar sua leitura: \"Que boa visão do campo você teve hoje\".", desmotivacion: "Expor seu ritmo pausado como algo que precisa ser mudado na frente do grupo." },
      { situacion: "Facilitar uma mudança", activador: "Explicar detalhadamente a lógica e as novas regras da posição.", desmotivacion: "Mudanças de planos repentinas que quebrem seu mapa mental do jogo." }
    ],
    reseteo: `Quando {nombre} comete um erro, sua mente tende a ficar "presa" analisando o ocorrido para que não volte a acontecer. Acompanhamento sugerido: Oferecer-lhe uma âncora técnica. Não dizer "já passou". Dizer-lhe: "Você analisou bem o passe, só faltou ajustar a direção pelo vento. Agora, volta a observar o centro". Ao dar-lhe um novo dado para processar, sua mente tende a sair do loop e voltar ao presente.`,
    ecos: `Em casa: Tende a precisar entender o "porquê" das coisas. É provável que não aceite um "porque sim". Costuma valorizar muito os jogos de estratégia, os puzzles ou qualquer atividade que exija pensar um plano. Na escola: Pode dar a impressão de estar no seu mundo, mas quando você pergunta, tem a resposta mais profunda. Tendem a encantá-lo as ciências, o xadrez ou a leitura, onde pode se imergir em sistemas lógicos.`,
    checklist: {
      antes: `Chegar com tempo. {nombre} tende a precisar observar o campo, o clima e o ambiente para se sentir seguro antes de começar.`,
      durante: `Usar um tom de voz calmo. Evitar as indicações constantes; confiar em seu processo interno de ajuste.`,
      despues: `Conversar sobre a tática. Perguntar: "O que foi o mais interessante que você notou hoje no outro time?". Isso valida sua identidade e reforça sua paixão pelo aspecto inteligente do esporte.`,
    },
  },
};

export const TENDENCIA_CONTENT_PT: Record<string, TendenciaTranslation> = {
  // ── D primário ────────────────────────────────────────────────────────────────
  D_I: {
    parrafo: `Além de seu impulso natural para a ação, {nombre} tende a ter uma sensibilidade especial para o clima emocional do grupo. É provável que não queira apenas resolver a jogada, mas que os demais se entusiasmem com a solução. Essa combinação sugere um perfil que lidera arrastando: sua energia tende a ser contagiante e sua maneira de motivar provavelmente passe mais pelo carisma do que pela autoridade. Quando o time precisa de um impulso de ânimo, é provável que {nombre} seja quem o ative de forma espontânea.`,
    palabrasPuenteExtra: ["Time", "Contagiar", "Juntos"],
    palabrasRuidoExtra: ["Faz sozinho", "Não fale", "Silêncio total"],
  },
  D_S: {
    parrafo: `Junto ao seu impulso de ação, {nombre} tende a mostrar uma preocupação genuína com o bem-estar do grupo. É provável que não queira apenas avançar rápido, mas garantir que ninguém fique para trás. Essa combinação sugere um perfil protetor: sua maneira de liderar provavelmente inclua olhar para os lados para verificar que todos estão bem antes de acelerar. Se você notar que freia seu próprio ritmo para esperar um companheiro, é provável que não seja indecisão, mas cuidado instintivo.`,
    palabrasPuenteExtra: ["Proteger", "Cuidar", "Todos juntos"],
    palabrasRuidoExtra: ["Deixa quem ficou para trás", "Não olhe para trás", "Cada um por si"],
  },
  D_C: {
    parrafo: `A ação de {nombre} tende a não ser impulsiva: por trás de sua rapidez provavelmente haja um processo de análise que ocorre em frações de segundo. Essa combinação sugere um perfil que age com precisão cirúrgica. É provável que lhe interesse não apenas fazer as coisas rápido, mas fazê-las bem. Pode se frustrar se sentir que a velocidade do jogo lhe impede de executar com a qualidade que visualiza internamente. Reconhecer a inteligência por trás de suas decisões rápidas tende a ser a forma mais efetiva de nutrir sua confiança.`,
    palabrasPuenteExtra: ["Precisão", "Inteligente", "Dado-chave"],
    palabrasRuidoExtra: ["Não pense tanto", "Não importa como", "Rápido e pronto"],
  },

  // ── I primário ────────────────────────────────────────────────────────────────
  I_D: {
    parrafo: `Além de sua natureza social, {nombre} tende a ter uma faísca de protagonismo que o impulsiona a tomar a iniciativa dentro do grupo. É provável que não queira apenas fazer parte do time, mas sentir que sua participação gera um impacto visível. Essa combinação sugere um perfil que conecta liderando: tende a ser aquele companheiro que propõe o jogo, organiza o grupo e garante que a energia não caia. Se sentir que sua contribuição passa despercebida, seu entusiasmo pode se apagar rapidamente.`,
    palabrasPuenteExtra: ["Protagonismo", "Sua ideia", "Liderar"],
    palabrasRuidoExtra: ["Fica de lado", "Só observa", "Sua opinião não importa"],
  },
  I_S: {
    parrafo: `A sociabilidade de {nombre} tende a vir acompanhada de uma sensibilidade profunda para como os outros se sentem. É provável que seja o primeiro a notar se um companheiro está triste ou se alguém ficou excluído de uma atividade. Essa combinação sugere um perfil de "cola emocional": sua presença tende a gerar coesão porque não busca apenas se divertir, mas que todos se divirtam. Quando o grupo atravessa um momento difícil, {nombre} provavelmente seja quem mantém o tecido emocional intacto.`,
    palabrasPuenteExtra: ["Cuidar do outro", "Incluir", "Bem-estar"],
    palabrasRuidoExtra: ["Não se preocupe com os outros", "Foca só em você", "Isso não é assunto seu"],
  },
  I_C: {
    parrafo: `Por trás do calor social de {nombre} tende a haver um observador atento. É provável que enquanto se conecta com seus companheiros, sua mente esteja registrando padrões: quem está confortável, quem precisa de apoio, qual dinâmica funciona e qual não. Essa combinação sugere um perfil que entende o grupo por dentro. Seu feedback tende a ser surpreendentemente preciso porque o constrói a partir da experiência compartilhada, não da distância. Pode ser um grande aliado do treinador se lhe for dado espaço para compartilhar o que observa.`,
    palabrasPuenteExtra: ["Observar", "Entender", "Notar"],
    palabrasRuidoExtra: ["Não analise", "Para de olhar", "Isso não importa"],
  },

  // ── S primário ────────────────────────────────────────────────────────────────
  S_D: {
    parrafo: `Embora {nombre} tenda a preferir a estabilidade, carrega dentro de si uma reserva de iniciativa que pode surpreender. É provável que nos momentos onde a situação exige ação imediata — quando um companheiro precisa de ajuda ou quando o time está em risco — seu impulso adormecido se ative com uma força inesperada. Essa combinação sugere um perfil de "reserva de emergência": sua ação tende a ser pontual mas contundente. Após esse estouro, é provável que volte ao seu ritmo calmo, quase como se nada tivesse acontecido.`,
    palabrasPuenteExtra: ["Momento-chave", "Reagir", "Sua força"],
    palabrasRuidoExtra: ["Nunca tome a iniciativa", "Fique sempre atrás", "Não intervenha"],
  },
  S_I: {
    parrafo: `A estabilidade de {nombre} tende a vir acompanhada de um calor natural para com seus companheiros. É provável que não busque ser o centro das atenções, mas que sua presença gere um efeito tranquilizador em quem o rodeia. Essa combinação sugere um perfil de acompanhamento silencioso: tende a estar sempre disponível, ouvir sem julgar e oferecer apoio sem que lhe peçam. Os companheiros provavelmente o busquem de forma intuitiva quando precisam se sentir seguros.`,
    palabrasPuenteExtra: ["Acompanhar", "Ouvir", "Estar presente"],
    palabrasRuidoExtra: ["Não se meta", "Isso não é com você", "Se afaste do grupo"],
  },
  S_C: {
    parrafo: `A estabilidade de {nombre} tende a ter uma base técnica sólida. É provável que sua constância não seja apenas emocional, mas também metódica: gosta de fazer as coisas da mesma maneira porque encontrou um sistema que funciona. Essa combinação sugere um perfil de "âncora técnica": o companheiro que sempre está em sua posição, que executa a rotina sem falhas e que traz tranquilidade ao grupo com sua previsibilidade. Se for pedido que mude seu método, é importante explicar-lhe o porquê técnico, não apenas o porquê emocional.`,
    palabrasPuenteExtra: ["Método", "Sistema", "Passo a passo"],
    palabrasRuidoExtra: ["Muda tudo", "Improvisa", "Esqueça o que você sabe"],
  },

  // ── C primário ────────────────────────────────────────────────────────────────
  C_D: {
    parrafo: `A análise de {nombre} tende a não ficar na observação: uma vez que compreende a situação, é provável que aja com uma determinação que surpreenda. Essa combinação sugere um perfil de "estrategista executor": não apenas projeta o plano, mas quer implementá-lo. Pode se frustrar se depois de encontrar a solução ideal, o time não a executa. Sua maneira de liderar tende a ser a partir da evidência: "vamos fazer assim porque os dados mostram que funciona". Validar tanto sua análise quanto seu impulso de execução tende a ser a chave para mantê-lo motivado.`,
    palabrasPuenteExtra: ["Executar", "Decidir", "Implementar"],
    palabrasRuidoExtra: ["Só pensa, não faça", "Espera indefinidamente", "Seu plano não importa"],
  },
  C_I: {
    parrafo: `Embora {nombre} tenda a processar a informação de forma interna, carrega dentro de si uma necessidade de compartilhar seus achados com o grupo. É provável que quando descobre algo — um padrão no adversário, uma melhoria técnica — queira contá-lo a seus companheiros. Essa combinação sugere um perfil de "tradutor tático": alguém que observa com profundidade e depois traduz sua análise para uma linguagem que o time pode usar. Se lhe for dado um espaço para compartilhar o que vê (um mini papel de assistente tático, por exemplo), sua motivação tende a se multiplicar.`,
    palabrasPuenteExtra: ["Compartilhar", "Explicar", "Ensinar"],
    palabrasRuidoExtra: ["Guarda pra você", "Ninguém quer saber disso", "Não explique"],
  },
  C_S: {
    parrafo: `O perfil analítico de {nombre} tende a estar acompanhado de uma paciência natural que lhe permite observar sem pressa. É provável que não precise de respostas imediatas: seu sistema se sente à vontade processando a informação até encontrar o momento certo para agir. Essa combinação sugere um perfil de "observador paciente": tende a ser o companheiro que nota detalhes que outros deixam passar precisamente porque não tem urgência para intervir. Sua contribuição ao time costuma ser silenciosa mas altamente valiosa quando é consultado.`,
    palabrasPuenteExtra: ["Paciência", "Observar", "Seu momento"],
    palabrasRuidoExtra: ["Se apresse", "Responde já", "Não perca tempo olhando"],
  },
};
