/**
 * Generates a styled HTML report for download, using the Argo Design System.
 * Separate from the email template (buildReportHtml) which uses email-safe inline styles.
 */

import type { ReportData } from './argosEngine';

/* ── DS Colors ─────────────────────────────────────────────────────────────── */
const C = {
    navy: '#1D1D1F',
    secondary: '#424245',
    grey: '#86868B',
    light: '#AEAEB2',
    border: '#E8E8ED',
    bg: '#F8F8FA',
    white: '#FFFFFF',
    violet500: '#955FB5',
    violet100: '#EDE5F5',
    violet50: '#F9F5FC',
    axisD: '#f97316', axisDfaded: 'rgba(249,115,22,0.12)',
    axisI: '#f59e0b', axisIfaded: 'rgba(245,158,11,0.12)',
    axisS: '#22c55e', axisSfaded: 'rgba(34,197,94,0.12)',
    axisC: '#6366f1', axisCfaded: 'rgba(99,102,241,0.12)',
};

const AXIS_COLOR: Record<string, { color: string; bg: string; border: string }> = {
    D: { color: C.axisD, bg: C.axisDfaded, border: 'rgba(249,115,22,0.25)' },
    I: { color: C.axisI, bg: C.axisIfaded, border: 'rgba(245,158,11,0.25)' },
    S: { color: C.axisS, bg: C.axisSfaded, border: 'rgba(34,197,94,0.25)' },
    C: { color: C.axisC, bg: C.axisCfaded, border: 'rgba(99,102,241,0.25)' },
};

interface DownloadReportOptions {
    report: ReportData;
    childName: string;
    childAge: number;
    sport: string;
    adultName: string;
    date: string;
    lang?: string;
}

export function buildDownloadableReportHtml(opts: DownloadReportOptions): string {
    const { report, childName, childAge, sport, adultName, date, lang = 'es' } = opts;
    const eje = report.arquetipo.eje;
    const ac = AXIS_COLOR[eje] ?? AXIS_COLOR.C;

    const labels = {
        es: {
            title: 'Informe de perfil',
            age: 'años', sport: 'Deporte', adult: 'Adulto responsable', date: 'Fecha',
            profile: 'Perfil', motor: 'Motor', compass: 'Brújula secundaria',
            bridgeWords: 'Palabras puente', noiseWords: 'Evitar en la comunicación',
            guide: 'Guía rápida', activate: 'Activar', consider: 'A considerar',
            checklist: 'Checklist de entrenamiento', before: 'Antes', during: 'Durante', after: 'Después',
            echoes: 'Ecos fuera de la cancha', reset: 'Consejo de reset',
            footer: 'Generado por Argo Method',
            tendencia: 'Tendencia',
        },
        en: {
            title: 'Profile report',
            age: 'years', sport: 'Sport', adult: 'Responsible adult', date: 'Date',
            profile: 'Profile', motor: 'Motor', compass: 'Secondary compass',
            bridgeWords: 'Bridge words', noiseWords: 'Avoid in communication',
            guide: 'Quick guide', activate: 'Activate', consider: 'To consider',
            checklist: 'Training checklist', before: 'Before', during: 'During', after: 'After',
            echoes: 'Echoes outside the field', reset: 'Reset advice',
            footer: 'Generated by Argo Method',
            tendencia: 'Tendency',
        },
        pt: {
            title: 'Relatório de perfil',
            age: 'anos', sport: 'Esporte', adult: 'Adulto responsável', date: 'Data',
            profile: 'Perfil', motor: 'Motor', compass: 'Bússola secundária',
            bridgeWords: 'Palavras ponte', noiseWords: 'Evitar na comunicação',
            guide: 'Guia rápido', activate: 'Ativar', consider: 'A considerar',
            checklist: 'Checklist de treino', before: 'Antes', during: 'Durante', after: 'Depois',
            echoes: 'Ecos fora do campo', reset: 'Conselho de reset',
            footer: 'Gerado pelo Argo Method',
            tendencia: 'Tendência',
        },
    };
    const t = labels[lang as keyof typeof labels] ?? labels.es;

    const pill = (text: string, color: string, bg: string, border: string) =>
        `<span style="display:inline-block;padding:4px 14px;border-radius:20px;font-size:12px;font-weight:500;color:${color};background:${bg};border:1px solid ${border};margin:3px 3px 3px 0;">${text}</span>`;

    const noisePill = (text: string) =>
        `<span style="display:inline-block;padding:4px 14px;border-radius:20px;font-size:12px;font-weight:500;color:#dc2626;background:rgba(220,38,38,0.06);border:1px solid rgba(220,38,38,0.2);margin:3px 3px 3px 0;">${text}</span>`;

    const sectionLabel = (text: string) =>
        `<p style="font-size:10px;font-weight:600;letter-spacing:0.1em;text-transform:uppercase;color:${C.light};margin:0 0 10px 0;">${text}</p>`;

    const bodyText = (text: string) =>
        `<p style="font-size:13px;color:${C.secondary};line-height:1.7;margin:0 0 8px 0;">${(text || '').replace(/\n/g, '<br/>')}</p>`;

    const digestBox = (text: string) =>
        `<div style="background:${C.bg};border-left:2px solid ${C.violet100};border-radius:0 10px 10px 0;padding:14px 18px;margin:12px 0;">
            <p style="font-size:13px;color:${C.secondary};line-height:1.7;margin:0;">${(text || '').replace(/\n/g, '<br/>')}</p>
        </div>`;

    const card = (content: string) =>
        `<div style="background:${C.white};border-radius:14px;padding:24px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,0.04);">${content}</div>`;

    // Strip callout markers for clean display
    const clean = (text: string) => {
        if (!text) return '';
        return text
            .replace(/Nota fundamental:[\s\S]*/i, '')
            .replace(/Nota de seguridad:[\s\S]*/i, '')
            .replace(/Invitación de sintonía:[\s\S]*/i, '')
            .replace(/Feedback de sintonía:[\s\S]*/i, '')
            .trim();
    };

    return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${t.title}. ${childName}</title>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', -apple-system, sans-serif; background: ${C.bg}; color: ${C.navy}; -webkit-font-smoothing: antialiased; }
    @media print { body { background: white; } .no-print { display: none; } }
</style>
</head>
<body>
<div style="max-width:720px;margin:0 auto;padding:40px 24px;">

    <!-- Header -->
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:32px;">
        <div>
            <p style="font-size:10px;font-weight:600;letter-spacing:0.1em;text-transform:uppercase;color:${C.light};margin-bottom:6px;">${t.title}</p>
            <h1 style="font-size:28px;font-weight:700;color:${C.navy};letter-spacing:-0.02em;margin:0;">${childName}</h1>
            <p style="font-size:13px;color:${C.grey};margin-top:4px;">${childAge} ${t.age}${sport ? `  ·  ${sport}` : ''}  ·  ${date}</p>
        </div>
        <div style="text-align:right;">
            <span style="font-size:17px;letter-spacing:-0.02em;"><span style="font-weight:800;">Argo</span><span style="font-weight:200;color:${C.grey};"> Method</span></span>
        </div>
    </div>

    <!-- Archetype hero -->
    ${card(`
        <div style="display:flex;align-items:center;gap:12px;margin-bottom:16px;">
            <span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:${ac.color};"></span>
            <span style="font-size:11px;font-weight:500;padding:4px 14px;border-radius:20px;border:1px solid ${ac.border};color:${ac.color};">${report.arquetipo.label}</span>
            ${report.tendenciaLabel ? `<span style="font-size:11px;color:${C.grey};font-style:italic;">${report.tendenciaLabel}</span>` : ''}
        </div>
        <p style="font-size:15px;font-weight:600;color:${C.navy};margin-bottom:8px;">${report.perfil}</p>
        ${digestBox(clean(report.bienvenida))}
    `)}

    <!-- Motor -->
    ${card(`
        ${sectionLabel(t.motor)}
        ${bodyText(clean(report.motorDesc))}
    `)}

    <!-- Bridge words + Noise words side by side -->
    <div style="display:flex;gap:16px;margin-bottom:16px;">
        <div style="flex:1;background:${C.white};border-radius:14px;padding:24px;box-shadow:0 1px 3px rgba(0,0,0,0.04);">
            ${sectionLabel(t.bridgeWords)}
            <div>${(report.palabrasPuente || []).map(w => pill(w, ac.color, ac.bg, ac.border)).join('')}${(report.palabrasPuenteExtra || []).map(w => pill(w, ac.color, ac.bg, ac.border)).join('')}</div>
        </div>
        <div style="flex:1;background:${C.white};border-radius:14px;padding:24px;box-shadow:0 1px 3px rgba(0,0,0,0.04);">
            ${sectionLabel(t.noiseWords)}
            <div>${(report.palabrasRuido || []).map(w => noisePill(w)).join('')}${(report.palabrasRuidoExtra || []).map(w => noisePill(w)).join('')}</div>
        </div>
    </div>

    <!-- Tendencia -->
    ${report.tendenciaParagraph ? card(`
        ${sectionLabel(`${t.tendencia}: ${report.tendenciaLabel ?? ''}`)}
        ${bodyText(report.tendenciaParagraph)}
    `) : ''}

    <!-- Combustible -->
    ${report.combustible ? card(`
        ${sectionLabel(lang === 'en' ? 'What drives them' : lang === 'pt' ? 'O que os motiva' : 'Que lo mueve')}
        ${bodyText(clean(report.combustible))}
    `) : ''}

    <!-- Coaching guide -->
    ${report.guia?.length ? card(`
        ${sectionLabel(t.guide)}
        ${report.guia.map(g => `
            <div style="background:${C.bg};border-radius:10px;padding:14px 16px;margin-bottom:8px;">
                <p style="font-size:13px;font-weight:600;color:${C.navy};margin:0 0 6px 0;">${g.situacion}</p>
                <p style="font-size:12px;color:#059669;margin:0 0 4px 0;"><strong>${t.activate}:</strong> ${g.activador}</p>
                <p style="font-size:12px;color:#dc2626;margin:0;"><strong>${t.consider}:</strong> ${g.desmotivacion}</p>
            </div>
        `).join('')}
    `) : ''}

    <!-- Checklist -->
    ${report.checklist ? `
    <div style="display:flex;gap:12px;margin-bottom:16px;">
        ${[
            { label: t.before, text: report.checklist.antes, color: C.violet500 },
            { label: t.during, text: report.checklist.durante, color: C.axisS },
            { label: t.after, text: report.checklist.despues, color: C.axisI },
        ].map(c => `
            <div style="flex:1;background:${C.white};border-radius:14px;padding:20px;box-shadow:0 1px 3px rgba(0,0,0,0.04);">
                <p style="font-size:10px;font-weight:700;text-transform:uppercase;color:${c.color};margin:0 0 8px 0;">${c.label}</p>
                <p style="font-size:12px;color:${C.grey};line-height:1.6;margin:0;">${c.text}</p>
            </div>
        `).join('')}
    </div>` : ''}

    <!-- Echoes -->
    ${report.ecos ? card(`
        ${sectionLabel(t.echoes)}
        ${bodyText(clean(report.ecos))}
    `) : ''}

    <!-- Reset -->
    ${report.reseteo ? card(`
        ${sectionLabel(t.reset)}
        ${bodyText(clean(report.reseteo))}
    `) : ''}

    <!-- Footer -->
    <div style="text-align:center;padding:24px 0 0;border-top:1px solid ${C.border};margin-top:8px;">
        <p style="font-size:10px;color:${C.light};">${t.footer} · argomethod.com</p>
        <p style="font-size:10px;color:${C.light};margin-top:4px;">${t.adult}: ${adultName}</p>
    </div>

</div>
</body>
</html>`;
}
