import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Link2, Printer, CheckCircle, Lock } from 'lucide-react';
import { getReportData, getLocalizedTendenciaContent, getLocalizedTendenciaLabel } from '../lib/argosEngine';
import type { AISections } from '../lib/openaiService';
import {
    classifyDecisionPattern,
    getPatternCopy,
    getPatternSectionLabel,
    getImplicationLabel,
} from '../lib/decisionPattern';
import { AXIS_COLORS, AXIS_CHIP, MOTOR_CHIP } from '../lib/designTokens';

// ─── Types ────────────────────────────────────────────────────────────────────

interface SessionData {
    id: string;
    child_name: string;
    child_age: number;
    sport: string | null;
    adult_name: string;
    eje: string;
    motor: string;
    eje_secundario: string | null;
    lang: string;
    answers: { axis: string; responseTimeMs: number }[] | null;
    created_at: string;
    ai_sections: AISections | null;
    tenant_plan?: string | null;
}

// ─── i18n ─────────────────────────────────────────────────────────────────────

const T = {
    es: {
        reportTitle: 'Informe de perfil',
        age: 'años',
        guardian: 'Adulto responsable',
        archetype: 'Arquetipo',
        motor: 'Motor',
        motorNames: { Rápido: 'Dinámico', Medio: 'Rítmico', Lento: 'Sereno' } as Record<string, string>,
        distribution: 'Composición del perfil',
        bridgeWords: 'Palabras puente',
        noiseWords: 'Evitar en la comunicación',
        motorSection: 'Motor de rendimiento',
        decisionPattern: 'Patrón de decisión',
        implication: 'Qué significa para el entrenamiento',
        tendency: 'Tendencia secundaria',
        fuel: 'Qué lo mueve',
        guide: 'Guía rápida',
        activate: 'Activar',
        consider: 'A considerar',
        checklist: 'Checklist de entrenamiento',
        before: 'Antes del entrenamiento',
        during: 'Durante la sesión',
        after: 'Después del partido',
        echoes: 'Ecos fuera de la cancha',
        reset: 'Consejo de reset',
        copyLink: 'Compartir',
        copied: 'Copiado',
        download: 'Imprimir',
        footer: 'Generado por Argo Method',
        footerNote: 'Este informe es una fotografía del presente, no una etiqueta permanente.',
        notFound: 'Informe no encontrado.',
        notFoundSub: 'El link puede haber expirado o ser inválido.',
        loading: 'Cargando informe...',
        lockedTitle: 'El informe completo incluye mucho más',
        lockedBody: 'Motor de rendimiento · Palabras clave · Patrón de decisión · Guía de entrenamiento · Checklist · Ecos fuera de la cancha',
        lockedCta: 'Contacta con quien te compartió este link para acceder al informe completo.',
    },
    en: {
        reportTitle: 'Profile report',
        age: 'years',
        guardian: 'Responsible adult',
        archetype: 'Archetype',
        motor: 'Engine',
        motorNames: { Rápido: 'Dynamic', Medio: 'Rhythmic', Lento: 'Serene' } as Record<string, string>,
        distribution: 'Profile composition',
        bridgeWords: 'Bridge words',
        noiseWords: 'Avoid in communication',
        motorSection: 'Performance engine',
        decisionPattern: 'Decision pattern',
        implication: 'What this means for training',
        tendency: 'Secondary tendency',
        fuel: 'What drives them',
        guide: 'Quick guide',
        activate: 'Activate',
        consider: 'To consider',
        checklist: 'Training checklist',
        before: 'Before training',
        during: 'During the session',
        after: 'After the game',
        echoes: 'Echoes outside the field',
        reset: 'Reset advice',
        copyLink: 'Share',
        copied: 'Copied',
        download: 'Print',
        footer: 'Generated by Argo Method',
        footerNote: 'This report is a snapshot of the present, not a permanent label.',
        notFound: 'Report not found.',
        notFoundSub: 'The link may have expired or be invalid.',
        loading: 'Loading report...',
        lockedTitle: 'The full report includes much more',
        lockedBody: 'Performance engine · Key words · Decision pattern · Training guide · Checklist · Echoes outside the field',
        lockedCta: 'Contact whoever shared this link to access the full report.',
    },
    pt: {
        reportTitle: 'Relatório de perfil',
        age: 'anos',
        guardian: 'Adulto responsável',
        archetype: 'Arquétipo',
        motor: 'Motor',
        motorNames: { Rápido: 'Dinâmico', Medio: 'Rítmico', Lento: 'Sereno' } as Record<string, string>,
        distribution: 'Composição do perfil',
        bridgeWords: 'Palavras ponte',
        noiseWords: 'Evitar na comunicação',
        motorSection: 'Motor de desempenho',
        decisionPattern: 'Padrão de decisão',
        implication: 'O que isso significa no treino',
        tendency: 'Tendência secundária',
        fuel: 'O que o motiva',
        guide: 'Guia rápido',
        activate: 'Ativar',
        consider: 'A considerar',
        checklist: 'Checklist de treino',
        before: 'Antes do treino',
        during: 'Durante a sessão',
        after: 'Depois do jogo',
        echoes: 'Ecos fora do campo',
        reset: 'Conselho de reset',
        copyLink: 'Compartilhar',
        copied: 'Copiado',
        download: 'Imprimir',
        footer: 'Gerado pelo Argo Method',
        footerNote: 'Este relatório é uma fotografia do presente, não um rótulo permanente.',
        notFound: 'Relatório não encontrado.',
        notFoundSub: 'O link pode ter expirado ou ser inválido.',
        loading: 'Carregando relatório...',
        lockedTitle: 'O relatório completo inclui muito mais',
        lockedBody: 'Motor de desempenho · Palavras-chave · Padrão de decisão · Guia de treino · Checklist · Ecos fora do campo',
        lockedCta: 'Entre em contato com quem compartilhou este link para acessar o relatório completo.',
    },
};

// ─── Sub-components ───────────────────────────────────────────────────────────

const SectionLabel: React.FC<{ children: React.ReactNode }> = ({ children }) => (
    <p className="text-[10px] font-semibold tracking-[0.1em] uppercase text-argo-light mb-2.5">{children}</p>
);

const Card: React.FC<{ children: React.ReactNode; className?: string }> = ({ children, className = '' }) => (
    <div className={`bg-white rounded-[14px] p-6 shadow-argo mb-4 ${className}`}>{children}</div>
);

// Renders body text with the first sentence bold for visual hierarchy
const BodyText: React.FC<{ children: string; leadBold?: boolean }> = ({ children, leadBold }) => {
    if (!leadBold) {
        return (
            <p className="text-sm text-argo-secondary leading-relaxed">
                {children.split('\n').map((line, i, arr) => (
                    <React.Fragment key={i}>{line}{i < arr.length - 1 && <br />}</React.Fragment>
                ))}
            </p>
        );
    }
    const dotIdx = children.indexOf('. ');
    if (dotIdx === -1 || dotIdx > 130) {
        return <p className="text-sm text-argo-secondary leading-relaxed">{children}</p>;
    }
    const lead = children.slice(0, dotIdx + 1);
    const rest = children.slice(dotIdx + 1);
    return (
        <p className="text-sm text-argo-secondary leading-relaxed">
            <span className="font-semibold text-argo-navy">{lead}</span>{rest}
        </p>
    );
};

const DigestBox: React.FC<{ children: string }> = ({ children }) => (
    <div className="bg-argo-bg border-l-2 border-argo-violet-100 rounded-r-xl pl-4 pr-3 py-3 mt-3">
        <p className="text-sm text-argo-secondary leading-relaxed">{children}</p>
    </div>
);

// ─── Axis distribution mini-bars ──────────────────────────────────────────────

const AXIS_LABELS_I18N: Record<string, Record<string, string>> = {
    es: { D: 'Impulsor', I: 'Conector', S: 'Sostén',    C: 'Estratega' },
    en: { D: 'Driver',   I: 'Connector', S: 'Supporter', C: 'Strategist' },
    pt: { D: 'Impulsor', I: 'Conector',  S: 'Sustento',  C: 'Estrategista' },
};

const AxisBars: React.FC<{
    answers: { axis: string }[];
    dominantEje: string;
    label: string;
    lang: string;
}> = ({ answers, dominantEje, label, lang }) => {
    const axisLabels = AXIS_LABELS_I18N[lang] ?? AXIS_LABELS_I18N.es;
    const counts = { D: 0, I: 0, S: 0, C: 0 };
    answers.forEach(a => { if (a.axis in counts) counts[a.axis as keyof typeof counts]++; });
    const maxCount = Math.max(...Object.values(counts), 1);

    return (
        <div className="mt-4 pt-4 border-t border-argo-border">
            <p className="text-[10px] font-semibold tracking-[0.1em] uppercase text-argo-light mb-3">{label}</p>
            <div className="space-y-2">
                {(['D', 'I', 'S', 'C'] as const).map(axis => {
                    const pct = (counts[axis] / maxCount) * 100;
                    const isDominant = axis === dominantEje;
                    return (
                        <div key={axis} className="flex items-center gap-3">
                            <span className="text-[11px] font-medium text-argo-grey w-20 flex-shrink-0">
                                {axisLabels[axis]}
                            </span>
                            <div className="flex-1 bg-argo-bg rounded-full h-2 overflow-hidden">
                                <div
                                    className="h-full rounded-full transition-all"
                                    style={{
                                        width: `${pct}%`,
                                        background: AXIS_COLORS[axis],
                                        opacity: isDominant ? 1 : 0.35,
                                    }}
                                />
                            </div>
                        </div>
                    );
                })}
            </div>
        </div>
    );
};

// ─── Main page ────────────────────────────────────────────────────────────────

export const ReportPage: React.FC = () => {
    const { sessionId } = useParams<{ sessionId: string }>();
    const [session, setSession] = useState<SessionData | null>(null);
    const [loading, setLoading] = useState(true);
    const [notFound, setNotFound] = useState(false);
    const [copied, setCopied] = useState(false);

    // noindex meta tag
    useEffect(() => {
        const meta = document.createElement('meta');
        meta.name = 'robots';
        meta.content = 'noindex, nofollow';
        document.head.appendChild(meta);
        return () => { document.head.removeChild(meta); };
    }, []);

    useEffect(() => {
        if (!sessionId) { setNotFound(true); setLoading(false); return; }

        // DEV mock — API not available locally
        if (import.meta.env.DEV) {
            setSession({
                id: sessionId,
                child_name: 'Lucas',
                child_age: 13,
                sport: 'Fútbol',
                adult_name: 'Marcelo García',
                eje: 'D',
                motor: 'Rápido',
                eje_secundario: 'I',
                lang: 'es',
                answers: [
                    ...Array.from({ length: 5 }, (_, i) => ({ axis: 'D', responseTimeMs: 1800 + i * 200 })),
                    ...Array.from({ length: 3 }, (_, i) => ({ axis: 'I', responseTimeMs: 2500 + i * 400 })),
                    ...Array.from({ length: 2 }, () => ({ axis: 'S', responseTimeMs: 4000 })),
                    ...Array.from({ length: 2 }, () => ({ axis: 'C', responseTimeMs: 5500 })),
                ],
                created_at: new Date().toISOString(),
                ai_sections: null,
            });
            setLoading(false);
            return;
        }

        fetch(`/api/report?id=${encodeURIComponent(sessionId)}`)
            .then(r => {
                if (!r.ok) { setNotFound(true); setLoading(false); return; }
                return r.json();
            })
            .then(data => {
                if (data) setSession(data);
                setLoading(false);
            })
            .catch(() => { setNotFound(true); setLoading(false); });
    }, [sessionId]);


    const handleCopy = () => {
        navigator.clipboard.writeText(window.location.href).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };

    if (loading) {
        return (
            <div className="min-h-screen bg-argo-neutral flex items-center justify-center">
                <p className="text-argo-grey text-sm animate-pulse">{T.es.loading}</p>
            </div>
        );
    }

    if (notFound || !session) {
        return (
            <div className="min-h-screen bg-argo-neutral flex flex-col items-center justify-center p-6 text-center">
                <div className="mb-6 flex items-center gap-1.5">
                    <span className="font-[800] text-lg tracking-tight text-argo-navy">Argo</span>
                    <span className="font-[100] text-lg text-argo-grey"> Method</span>
                </div>
                <p className="text-base font-semibold text-argo-navy mb-2">{T.es.notFound}</p>
                <p className="text-sm text-argo-grey">{T.es.notFoundSub}</p>
            </div>
        );
    }

    const lang = (session.lang || 'es') as keyof typeof T;
    const t = T[lang] ?? T.es;
    const axisColor = AXIS_COLORS[session.eje] ?? '#955FB5';
    const axisChip = AXIS_CHIP[session.eje] ?? 'bg-violet-50 text-violet-700 border-violet-200';
    const motorChip = MOTOR_CHIP[session.motor] ?? 'bg-violet-50 text-violet-700 border-violet-200';
    const motorDisplayName = t.motorNames[session.motor] ?? session.motor;

    const sessionLang = session.lang || 'es';
    const report = getReportData(session.eje, session.motor, session.eje_secundario ?? '', session.child_name, sessionLang);
    if (session.eje_secundario) {
        const tendencia = getLocalizedTendenciaContent(session.eje, session.eje_secundario, sessionLang);
        if (tendencia) {
            report.tendenciaLabel = getLocalizedTendenciaLabel(session.eje_secundario, sessionLang);
            report.tendenciaParagraph = tendencia.parrafo.replace(/\{nombre\}/g, session.child_name);
            report.palabrasPuenteExtra = tendencia.palabrasPuenteExtra;
            report.palabrasRuidoExtra = tendencia.palabrasRuidoExtra;
        }
    }

    // Merge AI-personalized sections from DB
    const aiSections = session.ai_sections;
    if (aiSections) {
        if (aiSections.perfil)             report.perfil              = aiSections.perfil;
        if (aiSections.label)              report.arquetipo.label     = aiSections.label;
        if (aiSections.bienvenida)         report.bienvenida          = aiSections.bienvenida;
        if (aiSections.motorDesc)          report.motorDesc           = aiSections.motorDesc;
        if (aiSections.combustible)        report.combustible         = aiSections.combustible;
        if (aiSections.ecos)               report.ecos                = aiSections.ecos;
        if (aiSections.reseteo)            report.reseteo             = aiSections.reseteo;
        if (aiSections.checklist)          report.checklist           = aiSections.checklist;
        if (aiSections.guia)               report.guia                = aiSections.guia;
        if (aiSections.palabrasPuente)     report.palabrasPuente      = aiSections.palabrasPuente;
        if (aiSections.palabrasRuido)      report.palabrasRuido       = aiSections.palabrasRuido;
        if (aiSections.tendenciaLabel)     report.tendenciaLabel      = aiSections.tendenciaLabel;
        if (aiSections.tendenciaParagraph) report.tendenciaParagraph  = aiSections.tendenciaParagraph;
        if (aiSections.palabrasPuenteExtra) report.palabrasPuenteExtra = aiSections.palabrasPuenteExtra;
        if (aiSections.palabrasRuidoExtra)  report.palabrasRuidoExtra  = aiSections.palabrasRuidoExtra;
    }

    const decisionPattern = session.answers?.length
        ? classifyDecisionPattern(session.answers)
        : null;

    const date = new Date(session.created_at).toLocaleDateString(
        lang === 'pt' ? 'pt-BR' : lang === 'en' ? 'en-US' : 'es-AR',
        { day: '2-digit', month: 'long', year: 'numeric' },
    );

    const allBridgeWords = [...(report.palabrasPuente || []), ...(report.palabrasPuenteExtra || [])];
    const allNoiseWords  = [...(report.palabrasRuido  || []), ...(report.palabrasRuidoExtra  || [])];

    const cleanText = (text: string) =>
        text
            .replace(/Nota fundamental:[\s\S]*/i, '')
            .replace(/Nota de seguridad:[\s\S]*/i, '')
            .replace(/Invitación de sintonía:[\s\S]*/i, '')
            .replace(/Feedback de sintonía:[\s\S]*/i, '')
            .replace(/Nota de acompañamiento:[\s\S]*/i, '')
            .trim();

    return (
        <div className="min-h-screen bg-argo-neutral" style={{ fontFamily: 'Inter, -apple-system, sans-serif' }}>

            {/* Print styles */}
            <style>{`@media print { .no-print { display: none !important; } body { background: white !important; } }`}</style>

            {/* Top bar */}
            <div className="no-print sticky top-0 z-10 bg-white border-b border-argo-border px-4 sm:px-6 py-3 flex items-center justify-between">
                <div className="flex items-center gap-1.5">
                    <span className="font-[800] text-base tracking-tight text-argo-navy">Argo</span>
                    <span className="font-[100] text-base text-argo-grey"> Method</span>
                    <span className="ml-1.5 bg-[#BBBCFF] text-argo-navy text-[9px] font-semibold px-1.5 py-0.5 rounded tracking-[0.05em]">beta</span>
                </div>
                <div className="flex items-center gap-2">
                    <button
                        onClick={handleCopy}
                        className="flex items-center gap-1.5 text-xs font-medium text-argo-secondary border border-argo-border px-3 py-1.5 rounded-lg hover:bg-argo-bg transition-colors"
                    >
                        {copied
                            ? <><CheckCircle size={13} className="text-green-600" />{t.copied}</>
                            : <><Link2 size={13} />{t.copyLink}</>
                        }
                    </button>
                    <button
                        onClick={() => window.print()}
                        className="flex items-center gap-1.5 text-xs font-medium text-argo-secondary border border-argo-border px-3 py-1.5 rounded-lg hover:bg-argo-bg transition-colors"
                    >
                        <Printer size={13} />{t.download}
                    </button>
                </div>
            </div>

            {/* Content */}
            <div className="max-w-2xl mx-auto px-4 py-8">

                {/* Page header */}
                <div className="mb-6">
                    <p className="text-[10px] font-semibold tracking-[0.1em] uppercase text-argo-light mb-1.5">{t.reportTitle}</p>
                    <h1 className="text-2xl font-bold text-argo-navy tracking-tight">{session.child_name}</h1>
                    <p className="text-sm text-argo-grey mt-1">
                        {session.child_age} {t.age}
                        {session.sport ? ` · ${session.sport}` : ''}
                        {' · '}{date}
                    </p>
                    <p className="text-xs text-argo-light mt-0.5">{t.guardian}: {session.adult_name}</p>
                </div>

                {/* 1. Archetype hero */}
                <Card>
                    <div className="flex items-center gap-3 mb-4 flex-wrap">
                        <span
                            className="inline-block w-2.5 h-2.5 rounded-full flex-shrink-0"
                            style={{ background: axisColor }}
                        />
                        <span className={`text-xs font-semibold px-3 py-1 rounded-full border ${axisChip}`}>
                            {report.arquetipo.label}
                        </span>
                        {report.tendenciaLabel && (
                            <span className="text-xs text-argo-grey italic">{report.tendenciaLabel}</span>
                        )}
                        <span className={`ml-auto text-xs font-semibold px-3 py-1 rounded-full border ${motorChip}`}>
                            {t.motor} {motorDisplayName}
                        </span>
                    </div>
                    <p className="text-base font-semibold text-argo-navy mb-3 leading-snug">{report.perfil}</p>
                    <DigestBox>{cleanText(report.bienvenida)}</DigestBox>

                    {/* Axis distribution */}
                    {(session.answers?.length ?? 0) > 0 && (
                        <AxisBars
                            answers={session.answers!}
                            dominantEje={session.eje}
                            label={t.distribution}
                            lang={lang}
                        />
                    )}
                </Card>

                {/* ── TRIAL LOCK: show upsell after first card ── */}
                {session.tenant_plan === 'trial' ? (
                    <div className="bg-white rounded-[14px] shadow-argo p-8 text-center space-y-4 mb-4">
                        <div className="w-10 h-10 rounded-xl bg-argo-violet-50 border border-argo-violet-100 flex items-center justify-center mx-auto">
                            <Lock size={18} className="text-argo-violet-500" />
                        </div>
                        <div className="space-y-2">
                            <h3 className="text-base font-semibold text-argo-navy">{t.lockedTitle}</h3>
                            <p className="text-xs text-argo-grey leading-relaxed max-w-xs mx-auto">{t.lockedBody}</p>
                        </div>
                        <div className="pt-2 border-t border-argo-border">
                            <p className="text-xs text-argo-light leading-relaxed max-w-xs mx-auto">{t.lockedCta}</p>
                        </div>
                    </div>
                ) : (
                    <>
                        {/* 2. Motor */}
                        <Card>
                            <SectionLabel>{t.motorSection}</SectionLabel>
                            <BodyText leadBold>{report.motorDesc}</BodyText>
                        </Card>

                        {/* 3. Combustible */}
                        {report.combustible && (
                            <Card>
                                <SectionLabel>{t.fuel}</SectionLabel>
                                <BodyText leadBold>{cleanText(report.combustible)}</BodyText>
                            </Card>
                        )}

                        {/* 4. Decision pattern */}
                        {decisionPattern && (() => {
                            const p = getPatternCopy(decisionPattern, lang);
                            return (
                                <Card>
                                    <SectionLabel>{getPatternSectionLabel(lang)}</SectionLabel>
                                    <p className="text-sm font-semibold text-argo-navy mb-1.5">{p.label}</p>
                                    <BodyText>{p.desc}</BodyText>
                                    <p className="text-[10px] font-semibold tracking-[0.08em] uppercase text-argo-light mt-3 mb-1.5">
                                        {getImplicationLabel(lang)}
                                    </p>
                                    <DigestBox>{p.imp}</DigestBox>
                                </Card>
                            );
                        })()}

                        {/* 5. Bridge words + Noise words */}
                        <div className="flex gap-3 mb-4 flex-col sm:flex-row">
                            <div className="flex-1 bg-white rounded-[14px] p-5 shadow-argo">
                                <SectionLabel>{t.bridgeWords}</SectionLabel>
                                <div className="flex flex-wrap gap-1.5">
                                    {allBridgeWords.map((w, i) => (
                                        <span key={i} className="text-xs font-semibold px-3 py-1.5 rounded-full border"
                                            style={{ color: axisColor, background: `${axisColor}14`, borderColor: `${axisColor}40` }}>
                                            {w}
                                        </span>
                                    ))}
                                </div>
                            </div>
                            <div className="flex-1 bg-white rounded-[14px] p-5 shadow-argo">
                                <SectionLabel>{t.noiseWords}</SectionLabel>
                                <div className="flex flex-wrap gap-1.5">
                                    {allNoiseWords.map((w, i) => (
                                        <span key={i} className="text-xs font-medium px-3 py-1.5 rounded-full border text-red-600 bg-red-50 border-red-200">
                                            {w}
                                        </span>
                                    ))}
                                </div>
                            </div>
                        </div>

                        {/* 6. Tendencia */}
                        {report.tendenciaParagraph && (
                            <Card>
                                <SectionLabel>{t.tendency}{report.tendenciaLabel ? `: ${report.tendenciaLabel}` : ''}</SectionLabel>
                                <BodyText leadBold>{report.tendenciaParagraph}</BodyText>
                            </Card>
                        )}

                        {/* 7. Coaching guide */}
                        {report.guia?.length > 0 && (
                            <Card>
                                <SectionLabel>{t.guide}</SectionLabel>
                                <div className="space-y-3">
                                    {report.guia.map((g, i) => (
                                        <div key={i} className="bg-argo-bg rounded-xl p-3.5">
                                            <p className="text-sm font-semibold text-argo-navy mb-2">{g.situacion}</p>
                                            <p className="text-xs text-green-700 mb-1.5 leading-relaxed">
                                                <span className="font-bold">{t.activate}: </span>{g.activador}
                                            </p>
                                            <p className="text-xs text-red-600 leading-relaxed">
                                                <span className="font-bold">{t.consider}: </span>{g.desmotivacion}
                                            </p>
                                        </div>
                                    ))}
                                </div>
                            </Card>
                        )}

                        {/* 8. Checklist */}
                        {report.checklist && (
                            <div className="flex gap-3 mb-4 flex-col sm:flex-row">
                                {[
                                    { label: t.before,  text: report.checklist.antes,   color: 'text-argo-violet-500', dot: '#955FB5' },
                                    { label: t.during,  text: report.checklist.durante, color: 'text-green-600',       dot: '#22c55e' },
                                    { label: t.after,   text: report.checklist.despues, color: 'text-amber-600',       dot: '#f59e0b' },
                                ].map(c => (
                                    <div key={c.label} className="flex-1 bg-white rounded-[14px] p-4 shadow-argo">
                                        <div className="flex items-center gap-1.5 mb-2.5">
                                            <span className="inline-block w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: c.dot }} />
                                            <p className={`text-[10px] font-bold uppercase tracking-wider ${c.color}`}>{c.label}</p>
                                        </div>
                                        <p className="text-xs text-argo-grey leading-relaxed">{c.text}</p>
                                    </div>
                                ))}
                            </div>
                        )}

                        {/* 9. Echoes */}
                        {report.ecos && (
                            <Card>
                                <SectionLabel>{t.echoes}</SectionLabel>
                                <BodyText leadBold>{cleanText(report.ecos)}</BodyText>
                            </Card>
                        )}

                        {/* 10. Reset */}
                        {report.reseteo && (
                            <Card>
                                <SectionLabel>{t.reset}</SectionLabel>
                                <BodyText leadBold>{cleanText(report.reseteo)}</BodyText>
                            </Card>
                        )}
                    </>
                )}

                {/* Footer */}
                <div className="border-t border-argo-border mt-4 pt-6 text-center">
                    <p className="text-xs text-argo-light">{t.footer} · argomethod.com</p>
                    <p className="text-xs text-argo-light mt-1">{t.footerNote}</p>
                </div>

            </div>
        </div>
    );
};
